import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import "./globals.css";

const inter=Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight:["400","600"]
});

const interTight=Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
  weight:["700","800"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${interTight.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
