
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model AppointmentStatus
 * 
 */
export type AppointmentStatus = Prisma.AppointmentStatusModel
/**
 * Model ProposalStatus
 * 
 */
export type ProposalStatus = Prisma.ProposalStatusModel
/**
 * Model EventModality
 * 
 */
export type EventModality = Prisma.EventModalityModel
/**
 * Model EventOrigin
 * 
 */
export type EventOrigin = Prisma.EventOriginModel
/**
 * Model EventStatus
 * 
 */
export type EventStatus = Prisma.EventStatusModel
/**
 * Model RegistrationStatus
 * 
 */
export type RegistrationStatus = Prisma.RegistrationStatusModel
/**
 * Model City
 * 
 */
export type City = Prisma.CityModel
/**
 * Model Company
 * 
 */
export type Company = Prisma.CompanyModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model UserRole
 * 
 */
export type UserRole = Prisma.UserRoleModel
/**
 * Model Education
 * 
 */
export type Education = Prisma.EducationModel
/**
 * Model WorkExperience
 * 
 */
export type WorkExperience = Prisma.WorkExperienceModel
/**
 * Model Skill
 * 
 */
export type Skill = Prisma.SkillModel
/**
 * Model UserSkill
 * 
 */
export type UserSkill = Prisma.UserSkillModel
/**
 * Model Certification
 * 
 */
export type Certification = Prisma.CertificationModel
/**
 * Model TechnicalArea
 * 
 */
export type TechnicalArea = Prisma.TechnicalAreaModel
/**
 * Model OrientationType
 * 
 */
export type OrientationType = Prisma.OrientationTypeModel
/**
 * Model MentorTechnicalArea
 * 
 */
export type MentorTechnicalArea = Prisma.MentorTechnicalAreaModel
/**
 * Model MentorOrientationType
 * 
 */
export type MentorOrientationType = Prisma.MentorOrientationTypeModel
/**
 * Model AvailabilityBlock
 * 
 */
export type AvailabilityBlock = Prisma.AvailabilityBlockModel
/**
 * Model BlockedDate
 * 
 */
export type BlockedDate = Prisma.BlockedDateModel
/**
 * Model Appointment
 * 
 */
export type Appointment = Prisma.AppointmentModel
/**
 * Model TimeProposal
 * 
 */
export type TimeProposal = Prisma.TimeProposalModel
/**
 * Model AppointmentHistory
 * 
 */
export type AppointmentHistory = Prisma.AppointmentHistoryModel
/**
 * Model Vacancy
 * 
 */
export type Vacancy = Prisma.VacancyModel
/**
 * Model EventCategory
 * 
 */
export type EventCategory = Prisma.EventCategoryModel
/**
 * Model Event
 * 
 */
export type Event = Prisma.EventModel
/**
 * Model EventRegistration
 * 
 */
export type EventRegistration = Prisma.EventRegistrationModel
/**
 * Model EventAttendance
 * 
 */
export type EventAttendance = Prisma.EventAttendanceModel
