
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/AppointmentStatus.js'
export type * from './models/ProposalStatus.js'
export type * from './models/EventModality.js'
export type * from './models/EventOrigin.js'
export type * from './models/EventStatus.js'
export type * from './models/RegistrationStatus.js'
export type * from './models/City.js'
export type * from './models/Company.js'
export type * from './models/User.js'
export type * from './models/Role.js'
export type * from './models/UserRole.js'
export type * from './models/Education.js'
export type * from './models/WorkExperience.js'
export type * from './models/Skill.js'
export type * from './models/UserSkill.js'
export type * from './models/Certification.js'
export type * from './models/TechnicalArea.js'
export type * from './models/OrientationType.js'
export type * from './models/MentorTechnicalArea.js'
export type * from './models/MentorOrientationType.js'
export type * from './models/AvailabilityBlock.js'
export type * from './models/BlockedDate.js'
export type * from './models/Appointment.js'
export type * from './models/TimeProposal.js'
export type * from './models/AppointmentHistory.js'
export type * from './models/Vacancy.js'
export type * from './models/EventCategory.js'
export type * from './models/Event.js'
export type * from './models/EventRegistration.js'
export type * from './models/EventAttendance.js'
export type * from './commonInputTypes.js'