export const EDUCATION_UI_TEXTS = {
  pageTitle: "Trayectoria",
  pageDescription: "Muestra tus estudios, experiencia, habilidades y certificaciones",
  listTitle: "Formación registrada",
  listDescription: "Puedes agregar varias entradas y actualizar cada una.",
  listFooter: "Los nuevos estudios aparecerán aquí después de guardar.",
  addButton: "Agregar información",
  editButton: "Editar",
  deleteButton: "Eliminar",
  deletingButton: "Eliminando...",
  createTitle: "Agregar formación",
  editTitle: "Editar formación",
  institutionLabel: "Institución",
  institutionPlaceholder: "Nombre de la institución",
  degreeLabel: "Título o carrera",
  degreePlaceholder: "Ej. Licenciatura en Informática",
  startDateLabel: "Desde",
  endDateLabel: "Hasta",
  descriptionLabel: "Descripción (opcional)",
  descriptionPlaceholder: "Agrega un detalle relevante de tus estudios",
  cancelButton: "Cancelar",
  saveButton: "Guardar formación",
  savingButton: "Guardando...",
  deleteTitle: "¿Eliminar esta formación?",
  deleteMessage: (degree: string) =>
    `Se eliminará "${degree}" de tu trayectoria. Esta acción no se puede deshacer.`,
};
