
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccessRequestStatus` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AccessRequestStatus
 * 
 */
export type AccessRequestStatusModel = runtime.Types.Result.DefaultSelection<Prisma.$AccessRequestStatusPayload>

export type AggregateAccessRequestStatus = {
  _count: AccessRequestStatusCountAggregateOutputType | null
  _min: AccessRequestStatusMinAggregateOutputType | null
  _max: AccessRequestStatusMaxAggregateOutputType | null
}

export type AccessRequestStatusMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccessRequestStatusMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccessRequestStatusCountAggregateOutputType = {
  id: number
  title: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccessRequestStatusMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AccessRequestStatusMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AccessRequestStatusCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccessRequestStatusAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccessRequestStatus to aggregate.
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestStatuses to fetch.
   */
  orderBy?: Prisma.AccessRequestStatusOrderByWithRelationInput | Prisma.AccessRequestStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccessRequestStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccessRequestStatuses
  **/
  _count?: true | AccessRequestStatusCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccessRequestStatusMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccessRequestStatusMaxAggregateInputType
}

export type GetAccessRequestStatusAggregateType<T extends AccessRequestStatusAggregateArgs> = {
      [P in keyof T & keyof AggregateAccessRequestStatus]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccessRequestStatus[P]>
    : Prisma.GetScalarType<T[P], AggregateAccessRequestStatus[P]>
}




export type AccessRequestStatusGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccessRequestStatusWhereInput
  orderBy?: Prisma.AccessRequestStatusOrderByWithAggregationInput | Prisma.AccessRequestStatusOrderByWithAggregationInput[]
  by: Prisma.AccessRequestStatusScalarFieldEnum[] | Prisma.AccessRequestStatusScalarFieldEnum
  having?: Prisma.AccessRequestStatusScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccessRequestStatusCountAggregateInputType | true
  _min?: AccessRequestStatusMinAggregateInputType
  _max?: AccessRequestStatusMaxAggregateInputType
}

export type AccessRequestStatusGroupByOutputType = {
  id: string
  title: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: AccessRequestStatusCountAggregateOutputType | null
  _min: AccessRequestStatusMinAggregateOutputType | null
  _max: AccessRequestStatusMaxAggregateOutputType | null
}

export type GetAccessRequestStatusGroupByPayload<T extends AccessRequestStatusGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccessRequestStatusGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccessRequestStatusGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccessRequestStatusGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccessRequestStatusGroupByOutputType[P]>
      }
    >
  >



export type AccessRequestStatusWhereInput = {
  AND?: Prisma.AccessRequestStatusWhereInput | Prisma.AccessRequestStatusWhereInput[]
  OR?: Prisma.AccessRequestStatusWhereInput[]
  NOT?: Prisma.AccessRequestStatusWhereInput | Prisma.AccessRequestStatusWhereInput[]
  id?: Prisma.UuidFilter<"AccessRequestStatus"> | string
  title?: Prisma.StringFilter<"AccessRequestStatus"> | string
  description?: Prisma.StringNullableFilter<"AccessRequestStatus"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccessRequestStatus"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessRequestStatus"> | Date | string
  accessRequests?: Prisma.AccessRequestListRelationFilter
}

export type AccessRequestStatusOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accessRequests?: Prisma.AccessRequestOrderByRelationAggregateInput
}

export type AccessRequestStatusWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.AccessRequestStatusWhereInput | Prisma.AccessRequestStatusWhereInput[]
  OR?: Prisma.AccessRequestStatusWhereInput[]
  NOT?: Prisma.AccessRequestStatusWhereInput | Prisma.AccessRequestStatusWhereInput[]
  description?: Prisma.StringNullableFilter<"AccessRequestStatus"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccessRequestStatus"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessRequestStatus"> | Date | string
  accessRequests?: Prisma.AccessRequestListRelationFilter
}, "id" | "title">

export type AccessRequestStatusOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccessRequestStatusCountOrderByAggregateInput
  _max?: Prisma.AccessRequestStatusMaxOrderByAggregateInput
  _min?: Prisma.AccessRequestStatusMinOrderByAggregateInput
}

export type AccessRequestStatusScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccessRequestStatusScalarWhereWithAggregatesInput | Prisma.AccessRequestStatusScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccessRequestStatusScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccessRequestStatusScalarWhereWithAggregatesInput | Prisma.AccessRequestStatusScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"AccessRequestStatus"> | string
  title?: Prisma.StringWithAggregatesFilter<"AccessRequestStatus"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"AccessRequestStatus"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccessRequestStatus"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccessRequestStatus"> | Date | string
}

export type AccessRequestStatusCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accessRequests?: Prisma.AccessRequestCreateNestedManyWithoutStatusInput
}

export type AccessRequestStatusUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accessRequests?: Prisma.AccessRequestUncheckedCreateNestedManyWithoutStatusInput
}

export type AccessRequestStatusUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessRequests?: Prisma.AccessRequestUpdateManyWithoutStatusNestedInput
}

export type AccessRequestStatusUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessRequests?: Prisma.AccessRequestUncheckedUpdateManyWithoutStatusNestedInput
}

export type AccessRequestStatusCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccessRequestStatusUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccessRequestStatusUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccessRequestStatusCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccessRequestStatusMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccessRequestStatusMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccessRequestStatusScalarRelationFilter = {
  is?: Prisma.AccessRequestStatusWhereInput
  isNot?: Prisma.AccessRequestStatusWhereInput
}

export type AccessRequestStatusCreateNestedOneWithoutAccessRequestsInput = {
  create?: Prisma.XOR<Prisma.AccessRequestStatusCreateWithoutAccessRequestsInput, Prisma.AccessRequestStatusUncheckedCreateWithoutAccessRequestsInput>
  connectOrCreate?: Prisma.AccessRequestStatusCreateOrConnectWithoutAccessRequestsInput
  connect?: Prisma.AccessRequestStatusWhereUniqueInput
}

export type AccessRequestStatusUpdateOneRequiredWithoutAccessRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.AccessRequestStatusCreateWithoutAccessRequestsInput, Prisma.AccessRequestStatusUncheckedCreateWithoutAccessRequestsInput>
  connectOrCreate?: Prisma.AccessRequestStatusCreateOrConnectWithoutAccessRequestsInput
  upsert?: Prisma.AccessRequestStatusUpsertWithoutAccessRequestsInput
  connect?: Prisma.AccessRequestStatusWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccessRequestStatusUpdateToOneWithWhereWithoutAccessRequestsInput, Prisma.AccessRequestStatusUpdateWithoutAccessRequestsInput>, Prisma.AccessRequestStatusUncheckedUpdateWithoutAccessRequestsInput>
}

export type AccessRequestStatusCreateWithoutAccessRequestsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccessRequestStatusUncheckedCreateWithoutAccessRequestsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccessRequestStatusCreateOrConnectWithoutAccessRequestsInput = {
  where: Prisma.AccessRequestStatusWhereUniqueInput
  create: Prisma.XOR<Prisma.AccessRequestStatusCreateWithoutAccessRequestsInput, Prisma.AccessRequestStatusUncheckedCreateWithoutAccessRequestsInput>
}

export type AccessRequestStatusUpsertWithoutAccessRequestsInput = {
  update: Prisma.XOR<Prisma.AccessRequestStatusUpdateWithoutAccessRequestsInput, Prisma.AccessRequestStatusUncheckedUpdateWithoutAccessRequestsInput>
  create: Prisma.XOR<Prisma.AccessRequestStatusCreateWithoutAccessRequestsInput, Prisma.AccessRequestStatusUncheckedCreateWithoutAccessRequestsInput>
  where?: Prisma.AccessRequestStatusWhereInput
}

export type AccessRequestStatusUpdateToOneWithWhereWithoutAccessRequestsInput = {
  where?: Prisma.AccessRequestStatusWhereInput
  data: Prisma.XOR<Prisma.AccessRequestStatusUpdateWithoutAccessRequestsInput, Prisma.AccessRequestStatusUncheckedUpdateWithoutAccessRequestsInput>
}

export type AccessRequestStatusUpdateWithoutAccessRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccessRequestStatusUncheckedUpdateWithoutAccessRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AccessRequestStatusCountOutputType
 */

export type AccessRequestStatusCountOutputType = {
  accessRequests: number
}

export type AccessRequestStatusCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessRequests?: boolean | AccessRequestStatusCountOutputTypeCountAccessRequestsArgs
}

/**
 * AccessRequestStatusCountOutputType without action
 */
export type AccessRequestStatusCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatusCountOutputType
   */
  select?: Prisma.AccessRequestStatusCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AccessRequestStatusCountOutputType without action
 */
export type AccessRequestStatusCountOutputTypeCountAccessRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccessRequestWhereInput
}


export type AccessRequestStatusSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accessRequests?: boolean | Prisma.AccessRequestStatus$accessRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.AccessRequestStatusCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accessRequestStatus"]>

export type AccessRequestStatusSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["accessRequestStatus"]>

export type AccessRequestStatusSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["accessRequestStatus"]>

export type AccessRequestStatusSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccessRequestStatusOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["accessRequestStatus"]>
export type AccessRequestStatusInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessRequests?: boolean | Prisma.AccessRequestStatus$accessRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.AccessRequestStatusCountOutputTypeDefaultArgs<ExtArgs>
}
export type AccessRequestStatusIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AccessRequestStatusIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AccessRequestStatusPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccessRequestStatus"
  objects: {
    accessRequests: Prisma.$AccessRequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accessRequestStatus"]>
  composites: {}
}

export type AccessRequestStatusGetPayload<S extends boolean | null | undefined | AccessRequestStatusDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload, S>

export type AccessRequestStatusCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccessRequestStatusFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccessRequestStatusCountAggregateInputType | true
  }

export interface AccessRequestStatusDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccessRequestStatus'], meta: { name: 'AccessRequestStatus' } }
  /**
   * Find zero or one AccessRequestStatus that matches the filter.
   * @param {AccessRequestStatusFindUniqueArgs} args - Arguments to find a AccessRequestStatus
   * @example
   * // Get one AccessRequestStatus
   * const accessRequestStatus = await prisma.accessRequestStatus.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccessRequestStatusFindUniqueArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccessRequestStatus that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccessRequestStatusFindUniqueOrThrowArgs} args - Arguments to find a AccessRequestStatus
   * @example
   * // Get one AccessRequestStatus
   * const accessRequestStatus = await prisma.accessRequestStatus.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccessRequestStatusFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccessRequestStatus that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusFindFirstArgs} args - Arguments to find a AccessRequestStatus
   * @example
   * // Get one AccessRequestStatus
   * const accessRequestStatus = await prisma.accessRequestStatus.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccessRequestStatusFindFirstArgs>(args?: Prisma.SelectSubset<T, AccessRequestStatusFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccessRequestStatus that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusFindFirstOrThrowArgs} args - Arguments to find a AccessRequestStatus
   * @example
   * // Get one AccessRequestStatus
   * const accessRequestStatus = await prisma.accessRequestStatus.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccessRequestStatusFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccessRequestStatusFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccessRequestStatuses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccessRequestStatuses
   * const accessRequestStatuses = await prisma.accessRequestStatus.findMany()
   * 
   * // Get first 10 AccessRequestStatuses
   * const accessRequestStatuses = await prisma.accessRequestStatus.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accessRequestStatusWithIdOnly = await prisma.accessRequestStatus.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccessRequestStatusFindManyArgs>(args?: Prisma.SelectSubset<T, AccessRequestStatusFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccessRequestStatus.
   * @param {AccessRequestStatusCreateArgs} args - Arguments to create a AccessRequestStatus.
   * @example
   * // Create one AccessRequestStatus
   * const AccessRequestStatus = await prisma.accessRequestStatus.create({
   *   data: {
   *     // ... data to create a AccessRequestStatus
   *   }
   * })
   * 
   */
  create<T extends AccessRequestStatusCreateArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusCreateArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccessRequestStatuses.
   * @param {AccessRequestStatusCreateManyArgs} args - Arguments to create many AccessRequestStatuses.
   * @example
   * // Create many AccessRequestStatuses
   * const accessRequestStatus = await prisma.accessRequestStatus.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccessRequestStatusCreateManyArgs>(args?: Prisma.SelectSubset<T, AccessRequestStatusCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccessRequestStatuses and returns the data saved in the database.
   * @param {AccessRequestStatusCreateManyAndReturnArgs} args - Arguments to create many AccessRequestStatuses.
   * @example
   * // Create many AccessRequestStatuses
   * const accessRequestStatus = await prisma.accessRequestStatus.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccessRequestStatuses and only return the `id`
   * const accessRequestStatusWithIdOnly = await prisma.accessRequestStatus.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccessRequestStatusCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccessRequestStatusCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccessRequestStatus.
   * @param {AccessRequestStatusDeleteArgs} args - Arguments to delete one AccessRequestStatus.
   * @example
   * // Delete one AccessRequestStatus
   * const AccessRequestStatus = await prisma.accessRequestStatus.delete({
   *   where: {
   *     // ... filter to delete one AccessRequestStatus
   *   }
   * })
   * 
   */
  delete<T extends AccessRequestStatusDeleteArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusDeleteArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccessRequestStatus.
   * @param {AccessRequestStatusUpdateArgs} args - Arguments to update one AccessRequestStatus.
   * @example
   * // Update one AccessRequestStatus
   * const accessRequestStatus = await prisma.accessRequestStatus.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccessRequestStatusUpdateArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusUpdateArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccessRequestStatuses.
   * @param {AccessRequestStatusDeleteManyArgs} args - Arguments to filter AccessRequestStatuses to delete.
   * @example
   * // Delete a few AccessRequestStatuses
   * const { count } = await prisma.accessRequestStatus.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccessRequestStatusDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccessRequestStatusDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccessRequestStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccessRequestStatuses
   * const accessRequestStatus = await prisma.accessRequestStatus.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccessRequestStatusUpdateManyArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccessRequestStatuses and returns the data updated in the database.
   * @param {AccessRequestStatusUpdateManyAndReturnArgs} args - Arguments to update many AccessRequestStatuses.
   * @example
   * // Update many AccessRequestStatuses
   * const accessRequestStatus = await prisma.accessRequestStatus.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccessRequestStatuses and only return the `id`
   * const accessRequestStatusWithIdOnly = await prisma.accessRequestStatus.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccessRequestStatusUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccessRequestStatus.
   * @param {AccessRequestStatusUpsertArgs} args - Arguments to update or create a AccessRequestStatus.
   * @example
   * // Update or create a AccessRequestStatus
   * const accessRequestStatus = await prisma.accessRequestStatus.upsert({
   *   create: {
   *     // ... data to create a AccessRequestStatus
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccessRequestStatus we want to update
   *   }
   * })
   */
  upsert<T extends AccessRequestStatusUpsertArgs>(args: Prisma.SelectSubset<T, AccessRequestStatusUpsertArgs<ExtArgs>>): Prisma.Prisma__AccessRequestStatusClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestStatusPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccessRequestStatuses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusCountArgs} args - Arguments to filter AccessRequestStatuses to count.
   * @example
   * // Count the number of AccessRequestStatuses
   * const count = await prisma.accessRequestStatus.count({
   *   where: {
   *     // ... the filter for the AccessRequestStatuses we want to count
   *   }
   * })
  **/
  count<T extends AccessRequestStatusCountArgs>(
    args?: Prisma.Subset<T, AccessRequestStatusCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccessRequestStatusCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccessRequestStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccessRequestStatusAggregateArgs>(args: Prisma.Subset<T, AccessRequestStatusAggregateArgs>): Prisma.PrismaPromise<GetAccessRequestStatusAggregateType<T>>

  /**
   * Group by AccessRequestStatus.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestStatusGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccessRequestStatusGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccessRequestStatusGroupByArgs['orderBy'] }
      : { orderBy?: AccessRequestStatusGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccessRequestStatusGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccessRequestStatusGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccessRequestStatus model
 */
readonly fields: AccessRequestStatusFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccessRequestStatus.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccessRequestStatusClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accessRequests<T extends Prisma.AccessRequestStatus$accessRequestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccessRequestStatus$accessRequestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccessRequestStatus model
 */
export interface AccessRequestStatusFieldRefs {
  readonly id: Prisma.FieldRef<"AccessRequestStatus", 'String'>
  readonly title: Prisma.FieldRef<"AccessRequestStatus", 'String'>
  readonly description: Prisma.FieldRef<"AccessRequestStatus", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccessRequestStatus", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccessRequestStatus", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccessRequestStatus findUnique
 */
export type AccessRequestStatusFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestStatus to fetch.
   */
  where: Prisma.AccessRequestStatusWhereUniqueInput
}

/**
 * AccessRequestStatus findUniqueOrThrow
 */
export type AccessRequestStatusFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestStatus to fetch.
   */
  where: Prisma.AccessRequestStatusWhereUniqueInput
}

/**
 * AccessRequestStatus findFirst
 */
export type AccessRequestStatusFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestStatus to fetch.
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestStatuses to fetch.
   */
  orderBy?: Prisma.AccessRequestStatusOrderByWithRelationInput | Prisma.AccessRequestStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccessRequestStatuses.
   */
  cursor?: Prisma.AccessRequestStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessRequestStatuses.
   */
  distinct?: Prisma.AccessRequestStatusScalarFieldEnum | Prisma.AccessRequestStatusScalarFieldEnum[]
}

/**
 * AccessRequestStatus findFirstOrThrow
 */
export type AccessRequestStatusFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestStatus to fetch.
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestStatuses to fetch.
   */
  orderBy?: Prisma.AccessRequestStatusOrderByWithRelationInput | Prisma.AccessRequestStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccessRequestStatuses.
   */
  cursor?: Prisma.AccessRequestStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessRequestStatuses.
   */
  distinct?: Prisma.AccessRequestStatusScalarFieldEnum | Prisma.AccessRequestStatusScalarFieldEnum[]
}

/**
 * AccessRequestStatus findMany
 */
export type AccessRequestStatusFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestStatuses to fetch.
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestStatuses to fetch.
   */
  orderBy?: Prisma.AccessRequestStatusOrderByWithRelationInput | Prisma.AccessRequestStatusOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccessRequestStatuses.
   */
  cursor?: Prisma.AccessRequestStatusWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestStatuses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestStatuses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessRequestStatuses.
   */
  distinct?: Prisma.AccessRequestStatusScalarFieldEnum | Prisma.AccessRequestStatusScalarFieldEnum[]
}

/**
 * AccessRequestStatus create
 */
export type AccessRequestStatusCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * The data needed to create a AccessRequestStatus.
   */
  data: Prisma.XOR<Prisma.AccessRequestStatusCreateInput, Prisma.AccessRequestStatusUncheckedCreateInput>
}

/**
 * AccessRequestStatus createMany
 */
export type AccessRequestStatusCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccessRequestStatuses.
   */
  data: Prisma.AccessRequestStatusCreateManyInput | Prisma.AccessRequestStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccessRequestStatus createManyAndReturn
 */
export type AccessRequestStatusCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * The data used to create many AccessRequestStatuses.
   */
  data: Prisma.AccessRequestStatusCreateManyInput | Prisma.AccessRequestStatusCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccessRequestStatus update
 */
export type AccessRequestStatusUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * The data needed to update a AccessRequestStatus.
   */
  data: Prisma.XOR<Prisma.AccessRequestStatusUpdateInput, Prisma.AccessRequestStatusUncheckedUpdateInput>
  /**
   * Choose, which AccessRequestStatus to update.
   */
  where: Prisma.AccessRequestStatusWhereUniqueInput
}

/**
 * AccessRequestStatus updateMany
 */
export type AccessRequestStatusUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccessRequestStatuses.
   */
  data: Prisma.XOR<Prisma.AccessRequestStatusUpdateManyMutationInput, Prisma.AccessRequestStatusUncheckedUpdateManyInput>
  /**
   * Filter which AccessRequestStatuses to update
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * Limit how many AccessRequestStatuses to update.
   */
  limit?: number
}

/**
 * AccessRequestStatus updateManyAndReturn
 */
export type AccessRequestStatusUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * The data used to update AccessRequestStatuses.
   */
  data: Prisma.XOR<Prisma.AccessRequestStatusUpdateManyMutationInput, Prisma.AccessRequestStatusUncheckedUpdateManyInput>
  /**
   * Filter which AccessRequestStatuses to update
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * Limit how many AccessRequestStatuses to update.
   */
  limit?: number
}

/**
 * AccessRequestStatus upsert
 */
export type AccessRequestStatusUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * The filter to search for the AccessRequestStatus to update in case it exists.
   */
  where: Prisma.AccessRequestStatusWhereUniqueInput
  /**
   * In case the AccessRequestStatus found by the `where` argument doesn't exist, create a new AccessRequestStatus with this data.
   */
  create: Prisma.XOR<Prisma.AccessRequestStatusCreateInput, Prisma.AccessRequestStatusUncheckedCreateInput>
  /**
   * In case the AccessRequestStatus was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccessRequestStatusUpdateInput, Prisma.AccessRequestStatusUncheckedUpdateInput>
}

/**
 * AccessRequestStatus delete
 */
export type AccessRequestStatusDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
  /**
   * Filter which AccessRequestStatus to delete.
   */
  where: Prisma.AccessRequestStatusWhereUniqueInput
}

/**
 * AccessRequestStatus deleteMany
 */
export type AccessRequestStatusDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccessRequestStatuses to delete
   */
  where?: Prisma.AccessRequestStatusWhereInput
  /**
   * Limit how many AccessRequestStatuses to delete.
   */
  limit?: number
}

/**
 * AccessRequestStatus.accessRequests
 */
export type AccessRequestStatus$accessRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequest
   */
  select?: Prisma.AccessRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequest
   */
  omit?: Prisma.AccessRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestInclude<ExtArgs> | null
  where?: Prisma.AccessRequestWhereInput
  orderBy?: Prisma.AccessRequestOrderByWithRelationInput | Prisma.AccessRequestOrderByWithRelationInput[]
  cursor?: Prisma.AccessRequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccessRequestScalarFieldEnum | Prisma.AccessRequestScalarFieldEnum[]
}

/**
 * AccessRequestStatus without action
 */
export type AccessRequestStatusDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestStatus
   */
  select?: Prisma.AccessRequestStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestStatus
   */
  omit?: Prisma.AccessRequestStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestStatusInclude<ExtArgs> | null
}
