
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccessRequestDocumentType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AccessRequestDocumentType
 * 
 */
export type AccessRequestDocumentTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$AccessRequestDocumentTypePayload>

export type AggregateAccessRequestDocumentType = {
  _count: AccessRequestDocumentTypeCountAggregateOutputType | null
  _min: AccessRequestDocumentTypeMinAggregateOutputType | null
  _max: AccessRequestDocumentTypeMaxAggregateOutputType | null
}

export type AccessRequestDocumentTypeMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccessRequestDocumentTypeMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccessRequestDocumentTypeCountAggregateOutputType = {
  id: number
  title: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccessRequestDocumentTypeMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AccessRequestDocumentTypeMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type AccessRequestDocumentTypeCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccessRequestDocumentTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccessRequestDocumentType to aggregate.
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestDocumentTypes to fetch.
   */
  orderBy?: Prisma.AccessRequestDocumentTypeOrderByWithRelationInput | Prisma.AccessRequestDocumentTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestDocumentTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestDocumentTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccessRequestDocumentTypes
  **/
  _count?: true | AccessRequestDocumentTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccessRequestDocumentTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccessRequestDocumentTypeMaxAggregateInputType
}

export type GetAccessRequestDocumentTypeAggregateType<T extends AccessRequestDocumentTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateAccessRequestDocumentType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccessRequestDocumentType[P]>
    : Prisma.GetScalarType<T[P], AggregateAccessRequestDocumentType[P]>
}




export type AccessRequestDocumentTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  orderBy?: Prisma.AccessRequestDocumentTypeOrderByWithAggregationInput | Prisma.AccessRequestDocumentTypeOrderByWithAggregationInput[]
  by: Prisma.AccessRequestDocumentTypeScalarFieldEnum[] | Prisma.AccessRequestDocumentTypeScalarFieldEnum
  having?: Prisma.AccessRequestDocumentTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccessRequestDocumentTypeCountAggregateInputType | true
  _min?: AccessRequestDocumentTypeMinAggregateInputType
  _max?: AccessRequestDocumentTypeMaxAggregateInputType
}

export type AccessRequestDocumentTypeGroupByOutputType = {
  id: string
  title: string
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: AccessRequestDocumentTypeCountAggregateOutputType | null
  _min: AccessRequestDocumentTypeMinAggregateOutputType | null
  _max: AccessRequestDocumentTypeMaxAggregateOutputType | null
}

export type GetAccessRequestDocumentTypeGroupByPayload<T extends AccessRequestDocumentTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccessRequestDocumentTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccessRequestDocumentTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccessRequestDocumentTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccessRequestDocumentTypeGroupByOutputType[P]>
      }
    >
  >



export type AccessRequestDocumentTypeWhereInput = {
  AND?: Prisma.AccessRequestDocumentTypeWhereInput | Prisma.AccessRequestDocumentTypeWhereInput[]
  OR?: Prisma.AccessRequestDocumentTypeWhereInput[]
  NOT?: Prisma.AccessRequestDocumentTypeWhereInput | Prisma.AccessRequestDocumentTypeWhereInput[]
  id?: Prisma.UuidFilter<"AccessRequestDocumentType"> | string
  title?: Prisma.StringFilter<"AccessRequestDocumentType"> | string
  description?: Prisma.StringNullableFilter<"AccessRequestDocumentType"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccessRequestDocumentType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessRequestDocumentType"> | Date | string
  accessRequests?: Prisma.AccessRequestListRelationFilter
}

export type AccessRequestDocumentTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  accessRequests?: Prisma.AccessRequestOrderByRelationAggregateInput
}

export type AccessRequestDocumentTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.AccessRequestDocumentTypeWhereInput | Prisma.AccessRequestDocumentTypeWhereInput[]
  OR?: Prisma.AccessRequestDocumentTypeWhereInput[]
  NOT?: Prisma.AccessRequestDocumentTypeWhereInput | Prisma.AccessRequestDocumentTypeWhereInput[]
  description?: Prisma.StringNullableFilter<"AccessRequestDocumentType"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccessRequestDocumentType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccessRequestDocumentType"> | Date | string
  accessRequests?: Prisma.AccessRequestListRelationFilter
}, "id" | "title">

export type AccessRequestDocumentTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccessRequestDocumentTypeCountOrderByAggregateInput
  _max?: Prisma.AccessRequestDocumentTypeMaxOrderByAggregateInput
  _min?: Prisma.AccessRequestDocumentTypeMinOrderByAggregateInput
}

export type AccessRequestDocumentTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccessRequestDocumentTypeScalarWhereWithAggregatesInput | Prisma.AccessRequestDocumentTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccessRequestDocumentTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccessRequestDocumentTypeScalarWhereWithAggregatesInput | Prisma.AccessRequestDocumentTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"AccessRequestDocumentType"> | string
  title?: Prisma.StringWithAggregatesFilter<"AccessRequestDocumentType"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"AccessRequestDocumentType"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccessRequestDocumentType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccessRequestDocumentType"> | Date | string
}

export type AccessRequestDocumentTypeCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accessRequests?: Prisma.AccessRequestCreateNestedManyWithoutDocumentTypeInput
}

export type AccessRequestDocumentTypeUncheckedCreateInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  accessRequests?: Prisma.AccessRequestUncheckedCreateNestedManyWithoutDocumentTypeInput
}

export type AccessRequestDocumentTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessRequests?: Prisma.AccessRequestUpdateManyWithoutDocumentTypeNestedInput
}

export type AccessRequestDocumentTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  accessRequests?: Prisma.AccessRequestUncheckedUpdateManyWithoutDocumentTypeNestedInput
}

export type AccessRequestDocumentTypeCreateManyInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccessRequestDocumentTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccessRequestDocumentTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccessRequestDocumentTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccessRequestDocumentTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccessRequestDocumentTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccessRequestDocumentTypeNullableScalarRelationFilter = {
  is?: Prisma.AccessRequestDocumentTypeWhereInput | null
  isNot?: Prisma.AccessRequestDocumentTypeWhereInput | null
}

export type AccessRequestDocumentTypeCreateNestedOneWithoutAccessRequestsInput = {
  create?: Prisma.XOR<Prisma.AccessRequestDocumentTypeCreateWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUncheckedCreateWithoutAccessRequestsInput>
  connectOrCreate?: Prisma.AccessRequestDocumentTypeCreateOrConnectWithoutAccessRequestsInput
  connect?: Prisma.AccessRequestDocumentTypeWhereUniqueInput
}

export type AccessRequestDocumentTypeUpdateOneWithoutAccessRequestsNestedInput = {
  create?: Prisma.XOR<Prisma.AccessRequestDocumentTypeCreateWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUncheckedCreateWithoutAccessRequestsInput>
  connectOrCreate?: Prisma.AccessRequestDocumentTypeCreateOrConnectWithoutAccessRequestsInput
  upsert?: Prisma.AccessRequestDocumentTypeUpsertWithoutAccessRequestsInput
  disconnect?: Prisma.AccessRequestDocumentTypeWhereInput | boolean
  delete?: Prisma.AccessRequestDocumentTypeWhereInput | boolean
  connect?: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateToOneWithWhereWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUpdateWithoutAccessRequestsInput>, Prisma.AccessRequestDocumentTypeUncheckedUpdateWithoutAccessRequestsInput>
}

export type AccessRequestDocumentTypeCreateWithoutAccessRequestsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccessRequestDocumentTypeUncheckedCreateWithoutAccessRequestsInput = {
  id?: string
  title: string
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccessRequestDocumentTypeCreateOrConnectWithoutAccessRequestsInput = {
  where: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.AccessRequestDocumentTypeCreateWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUncheckedCreateWithoutAccessRequestsInput>
}

export type AccessRequestDocumentTypeUpsertWithoutAccessRequestsInput = {
  update: Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUncheckedUpdateWithoutAccessRequestsInput>
  create: Prisma.XOR<Prisma.AccessRequestDocumentTypeCreateWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUncheckedCreateWithoutAccessRequestsInput>
  where?: Prisma.AccessRequestDocumentTypeWhereInput
}

export type AccessRequestDocumentTypeUpdateToOneWithWhereWithoutAccessRequestsInput = {
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  data: Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateWithoutAccessRequestsInput, Prisma.AccessRequestDocumentTypeUncheckedUpdateWithoutAccessRequestsInput>
}

export type AccessRequestDocumentTypeUpdateWithoutAccessRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccessRequestDocumentTypeUncheckedUpdateWithoutAccessRequestsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AccessRequestDocumentTypeCountOutputType
 */

export type AccessRequestDocumentTypeCountOutputType = {
  accessRequests: number
}

export type AccessRequestDocumentTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessRequests?: boolean | AccessRequestDocumentTypeCountOutputTypeCountAccessRequestsArgs
}

/**
 * AccessRequestDocumentTypeCountOutputType without action
 */
export type AccessRequestDocumentTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentTypeCountOutputType
   */
  select?: Prisma.AccessRequestDocumentTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AccessRequestDocumentTypeCountOutputType without action
 */
export type AccessRequestDocumentTypeCountOutputTypeCountAccessRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccessRequestWhereInput
}


export type AccessRequestDocumentTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  accessRequests?: boolean | Prisma.AccessRequestDocumentType$accessRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.AccessRequestDocumentTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["accessRequestDocumentType"]>

export type AccessRequestDocumentTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["accessRequestDocumentType"]>

export type AccessRequestDocumentTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["accessRequestDocumentType"]>

export type AccessRequestDocumentTypeSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccessRequestDocumentTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["accessRequestDocumentType"]>
export type AccessRequestDocumentTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  accessRequests?: boolean | Prisma.AccessRequestDocumentType$accessRequestsArgs<ExtArgs>
  _count?: boolean | Prisma.AccessRequestDocumentTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type AccessRequestDocumentTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AccessRequestDocumentTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AccessRequestDocumentTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccessRequestDocumentType"
  objects: {
    accessRequests: Prisma.$AccessRequestPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accessRequestDocumentType"]>
  composites: {}
}

export type AccessRequestDocumentTypeGetPayload<S extends boolean | null | undefined | AccessRequestDocumentTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload, S>

export type AccessRequestDocumentTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccessRequestDocumentTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccessRequestDocumentTypeCountAggregateInputType | true
  }

export interface AccessRequestDocumentTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccessRequestDocumentType'], meta: { name: 'AccessRequestDocumentType' } }
  /**
   * Find zero or one AccessRequestDocumentType that matches the filter.
   * @param {AccessRequestDocumentTypeFindUniqueArgs} args - Arguments to find a AccessRequestDocumentType
   * @example
   * // Get one AccessRequestDocumentType
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccessRequestDocumentTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccessRequestDocumentType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccessRequestDocumentTypeFindUniqueOrThrowArgs} args - Arguments to find a AccessRequestDocumentType
   * @example
   * // Get one AccessRequestDocumentType
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccessRequestDocumentTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccessRequestDocumentType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeFindFirstArgs} args - Arguments to find a AccessRequestDocumentType
   * @example
   * // Get one AccessRequestDocumentType
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccessRequestDocumentTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, AccessRequestDocumentTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccessRequestDocumentType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeFindFirstOrThrowArgs} args - Arguments to find a AccessRequestDocumentType
   * @example
   * // Get one AccessRequestDocumentType
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccessRequestDocumentTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccessRequestDocumentTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccessRequestDocumentTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccessRequestDocumentTypes
   * const accessRequestDocumentTypes = await prisma.accessRequestDocumentType.findMany()
   * 
   * // Get first 10 AccessRequestDocumentTypes
   * const accessRequestDocumentTypes = await prisma.accessRequestDocumentType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accessRequestDocumentTypeWithIdOnly = await prisma.accessRequestDocumentType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccessRequestDocumentTypeFindManyArgs>(args?: Prisma.SelectSubset<T, AccessRequestDocumentTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccessRequestDocumentType.
   * @param {AccessRequestDocumentTypeCreateArgs} args - Arguments to create a AccessRequestDocumentType.
   * @example
   * // Create one AccessRequestDocumentType
   * const AccessRequestDocumentType = await prisma.accessRequestDocumentType.create({
   *   data: {
   *     // ... data to create a AccessRequestDocumentType
   *   }
   * })
   * 
   */
  create<T extends AccessRequestDocumentTypeCreateArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeCreateArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccessRequestDocumentTypes.
   * @param {AccessRequestDocumentTypeCreateManyArgs} args - Arguments to create many AccessRequestDocumentTypes.
   * @example
   * // Create many AccessRequestDocumentTypes
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccessRequestDocumentTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, AccessRequestDocumentTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccessRequestDocumentTypes and returns the data saved in the database.
   * @param {AccessRequestDocumentTypeCreateManyAndReturnArgs} args - Arguments to create many AccessRequestDocumentTypes.
   * @example
   * // Create many AccessRequestDocumentTypes
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccessRequestDocumentTypes and only return the `id`
   * const accessRequestDocumentTypeWithIdOnly = await prisma.accessRequestDocumentType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccessRequestDocumentTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccessRequestDocumentTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccessRequestDocumentType.
   * @param {AccessRequestDocumentTypeDeleteArgs} args - Arguments to delete one AccessRequestDocumentType.
   * @example
   * // Delete one AccessRequestDocumentType
   * const AccessRequestDocumentType = await prisma.accessRequestDocumentType.delete({
   *   where: {
   *     // ... filter to delete one AccessRequestDocumentType
   *   }
   * })
   * 
   */
  delete<T extends AccessRequestDocumentTypeDeleteArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccessRequestDocumentType.
   * @param {AccessRequestDocumentTypeUpdateArgs} args - Arguments to update one AccessRequestDocumentType.
   * @example
   * // Update one AccessRequestDocumentType
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccessRequestDocumentTypeUpdateArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccessRequestDocumentTypes.
   * @param {AccessRequestDocumentTypeDeleteManyArgs} args - Arguments to filter AccessRequestDocumentTypes to delete.
   * @example
   * // Delete a few AccessRequestDocumentTypes
   * const { count } = await prisma.accessRequestDocumentType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccessRequestDocumentTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccessRequestDocumentTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccessRequestDocumentTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccessRequestDocumentTypes
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccessRequestDocumentTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccessRequestDocumentTypes and returns the data updated in the database.
   * @param {AccessRequestDocumentTypeUpdateManyAndReturnArgs} args - Arguments to update many AccessRequestDocumentTypes.
   * @example
   * // Update many AccessRequestDocumentTypes
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccessRequestDocumentTypes and only return the `id`
   * const accessRequestDocumentTypeWithIdOnly = await prisma.accessRequestDocumentType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccessRequestDocumentTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccessRequestDocumentType.
   * @param {AccessRequestDocumentTypeUpsertArgs} args - Arguments to update or create a AccessRequestDocumentType.
   * @example
   * // Update or create a AccessRequestDocumentType
   * const accessRequestDocumentType = await prisma.accessRequestDocumentType.upsert({
   *   create: {
   *     // ... data to create a AccessRequestDocumentType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccessRequestDocumentType we want to update
   *   }
   * })
   */
  upsert<T extends AccessRequestDocumentTypeUpsertArgs>(args: Prisma.SelectSubset<T, AccessRequestDocumentTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__AccessRequestDocumentTypeClient<runtime.Types.Result.GetResult<Prisma.$AccessRequestDocumentTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccessRequestDocumentTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeCountArgs} args - Arguments to filter AccessRequestDocumentTypes to count.
   * @example
   * // Count the number of AccessRequestDocumentTypes
   * const count = await prisma.accessRequestDocumentType.count({
   *   where: {
   *     // ... the filter for the AccessRequestDocumentTypes we want to count
   *   }
   * })
  **/
  count<T extends AccessRequestDocumentTypeCountArgs>(
    args?: Prisma.Subset<T, AccessRequestDocumentTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccessRequestDocumentTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccessRequestDocumentType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccessRequestDocumentTypeAggregateArgs>(args: Prisma.Subset<T, AccessRequestDocumentTypeAggregateArgs>): Prisma.PrismaPromise<GetAccessRequestDocumentTypeAggregateType<T>>

  /**
   * Group by AccessRequestDocumentType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccessRequestDocumentTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccessRequestDocumentTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccessRequestDocumentTypeGroupByArgs['orderBy'] }
      : { orderBy?: AccessRequestDocumentTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccessRequestDocumentTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccessRequestDocumentTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccessRequestDocumentType model
 */
readonly fields: AccessRequestDocumentTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccessRequestDocumentType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccessRequestDocumentTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  accessRequests<T extends Prisma.AccessRequestDocumentType$accessRequestsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccessRequestDocumentType$accessRequestsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccessRequestPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccessRequestDocumentType model
 */
export interface AccessRequestDocumentTypeFieldRefs {
  readonly id: Prisma.FieldRef<"AccessRequestDocumentType", 'String'>
  readonly title: Prisma.FieldRef<"AccessRequestDocumentType", 'String'>
  readonly description: Prisma.FieldRef<"AccessRequestDocumentType", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccessRequestDocumentType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccessRequestDocumentType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccessRequestDocumentType findUnique
 */
export type AccessRequestDocumentTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestDocumentType to fetch.
   */
  where: Prisma.AccessRequestDocumentTypeWhereUniqueInput
}

/**
 * AccessRequestDocumentType findUniqueOrThrow
 */
export type AccessRequestDocumentTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestDocumentType to fetch.
   */
  where: Prisma.AccessRequestDocumentTypeWhereUniqueInput
}

/**
 * AccessRequestDocumentType findFirst
 */
export type AccessRequestDocumentTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestDocumentType to fetch.
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestDocumentTypes to fetch.
   */
  orderBy?: Prisma.AccessRequestDocumentTypeOrderByWithRelationInput | Prisma.AccessRequestDocumentTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccessRequestDocumentTypes.
   */
  cursor?: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestDocumentTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestDocumentTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessRequestDocumentTypes.
   */
  distinct?: Prisma.AccessRequestDocumentTypeScalarFieldEnum | Prisma.AccessRequestDocumentTypeScalarFieldEnum[]
}

/**
 * AccessRequestDocumentType findFirstOrThrow
 */
export type AccessRequestDocumentTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestDocumentType to fetch.
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestDocumentTypes to fetch.
   */
  orderBy?: Prisma.AccessRequestDocumentTypeOrderByWithRelationInput | Prisma.AccessRequestDocumentTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccessRequestDocumentTypes.
   */
  cursor?: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestDocumentTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestDocumentTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessRequestDocumentTypes.
   */
  distinct?: Prisma.AccessRequestDocumentTypeScalarFieldEnum | Prisma.AccessRequestDocumentTypeScalarFieldEnum[]
}

/**
 * AccessRequestDocumentType findMany
 */
export type AccessRequestDocumentTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * Filter, which AccessRequestDocumentTypes to fetch.
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccessRequestDocumentTypes to fetch.
   */
  orderBy?: Prisma.AccessRequestDocumentTypeOrderByWithRelationInput | Prisma.AccessRequestDocumentTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccessRequestDocumentTypes.
   */
  cursor?: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccessRequestDocumentTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccessRequestDocumentTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccessRequestDocumentTypes.
   */
  distinct?: Prisma.AccessRequestDocumentTypeScalarFieldEnum | Prisma.AccessRequestDocumentTypeScalarFieldEnum[]
}

/**
 * AccessRequestDocumentType create
 */
export type AccessRequestDocumentTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a AccessRequestDocumentType.
   */
  data: Prisma.XOR<Prisma.AccessRequestDocumentTypeCreateInput, Prisma.AccessRequestDocumentTypeUncheckedCreateInput>
}

/**
 * AccessRequestDocumentType createMany
 */
export type AccessRequestDocumentTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccessRequestDocumentTypes.
   */
  data: Prisma.AccessRequestDocumentTypeCreateManyInput | Prisma.AccessRequestDocumentTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccessRequestDocumentType createManyAndReturn
 */
export type AccessRequestDocumentTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * The data used to create many AccessRequestDocumentTypes.
   */
  data: Prisma.AccessRequestDocumentTypeCreateManyInput | Prisma.AccessRequestDocumentTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccessRequestDocumentType update
 */
export type AccessRequestDocumentTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a AccessRequestDocumentType.
   */
  data: Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateInput, Prisma.AccessRequestDocumentTypeUncheckedUpdateInput>
  /**
   * Choose, which AccessRequestDocumentType to update.
   */
  where: Prisma.AccessRequestDocumentTypeWhereUniqueInput
}

/**
 * AccessRequestDocumentType updateMany
 */
export type AccessRequestDocumentTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccessRequestDocumentTypes.
   */
  data: Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateManyMutationInput, Prisma.AccessRequestDocumentTypeUncheckedUpdateManyInput>
  /**
   * Filter which AccessRequestDocumentTypes to update
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * Limit how many AccessRequestDocumentTypes to update.
   */
  limit?: number
}

/**
 * AccessRequestDocumentType updateManyAndReturn
 */
export type AccessRequestDocumentTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * The data used to update AccessRequestDocumentTypes.
   */
  data: Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateManyMutationInput, Prisma.AccessRequestDocumentTypeUncheckedUpdateManyInput>
  /**
   * Filter which AccessRequestDocumentTypes to update
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * Limit how many AccessRequestDocumentTypes to update.
   */
  limit?: number
}

/**
 * AccessRequestDocumentType upsert
 */
export type AccessRequestDocumentTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the AccessRequestDocumentType to update in case it exists.
   */
  where: Prisma.AccessRequestDocumentTypeWhereUniqueInput
  /**
   * In case the AccessRequestDocumentType found by the `where` argument doesn't exist, create a new AccessRequestDocumentType with this data.
   */
  create: Prisma.XOR<Prisma.AccessRequestDocumentTypeCreateInput, Prisma.AccessRequestDocumentTypeUncheckedCreateInput>
  /**
   * In case the AccessRequestDocumentType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccessRequestDocumentTypeUpdateInput, Prisma.AccessRequestDocumentTypeUncheckedUpdateInput>
}

/**
 * AccessRequestDocumentType delete
 */
export type AccessRequestDocumentTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
  /**
   * Filter which AccessRequestDocumentType to delete.
   */
  where: Prisma.AccessRequestDocumentTypeWhereUniqueInput
}

/**
 * AccessRequestDocumentType deleteMany
 */
export type AccessRequestDocumentTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccessRequestDocumentTypes to delete
   */
  where?: Prisma.AccessRequestDocumentTypeWhereInput
  /**
   * Limit how many AccessRequestDocumentTypes to delete.
   */
  limit?: number
}

/**
 * AccessRequestDocumentType.accessRequests
 */
export type AccessRequestDocumentType$accessRequestsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequest
   */
  select?: Prisma.AccessRequestSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequest
   */
  omit?: Prisma.AccessRequestOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestInclude<ExtArgs> | null
  where?: Prisma.AccessRequestWhereInput
  orderBy?: Prisma.AccessRequestOrderByWithRelationInput | Prisma.AccessRequestOrderByWithRelationInput[]
  cursor?: Prisma.AccessRequestWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AccessRequestScalarFieldEnum | Prisma.AccessRequestScalarFieldEnum[]
}

/**
 * AccessRequestDocumentType without action
 */
export type AccessRequestDocumentTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccessRequestDocumentType
   */
  select?: Prisma.AccessRequestDocumentTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccessRequestDocumentType
   */
  omit?: Prisma.AccessRequestDocumentTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccessRequestDocumentTypeInclude<ExtArgs> | null
}
