
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ApplicationHistory` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ApplicationHistory
 * 
 */
export type ApplicationHistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$ApplicationHistoryPayload>

export type AggregateApplicationHistory = {
  _count: ApplicationHistoryCountAggregateOutputType | null
  _min: ApplicationHistoryMinAggregateOutputType | null
  _max: ApplicationHistoryMaxAggregateOutputType | null
}

export type ApplicationHistoryMinAggregateOutputType = {
  id: string | null
  applicationId: string | null
  previousStatusId: string | null
  newStatusId: string | null
  changedById: string | null
  changedAt: Date | null
}

export type ApplicationHistoryMaxAggregateOutputType = {
  id: string | null
  applicationId: string | null
  previousStatusId: string | null
  newStatusId: string | null
  changedById: string | null
  changedAt: Date | null
}

export type ApplicationHistoryCountAggregateOutputType = {
  id: number
  applicationId: number
  previousStatusId: number
  newStatusId: number
  changedById: number
  changedAt: number
  _all: number
}


export type ApplicationHistoryMinAggregateInputType = {
  id?: true
  applicationId?: true
  previousStatusId?: true
  newStatusId?: true
  changedById?: true
  changedAt?: true
}

export type ApplicationHistoryMaxAggregateInputType = {
  id?: true
  applicationId?: true
  previousStatusId?: true
  newStatusId?: true
  changedById?: true
  changedAt?: true
}

export type ApplicationHistoryCountAggregateInputType = {
  id?: true
  applicationId?: true
  previousStatusId?: true
  newStatusId?: true
  changedById?: true
  changedAt?: true
  _all?: true
}

export type ApplicationHistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationHistory to aggregate.
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationHistories to fetch.
   */
  orderBy?: Prisma.ApplicationHistoryOrderByWithRelationInput | Prisma.ApplicationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ApplicationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ApplicationHistories
  **/
  _count?: true | ApplicationHistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ApplicationHistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ApplicationHistoryMaxAggregateInputType
}

export type GetApplicationHistoryAggregateType<T extends ApplicationHistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateApplicationHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateApplicationHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateApplicationHistory[P]>
}




export type ApplicationHistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationHistoryWhereInput
  orderBy?: Prisma.ApplicationHistoryOrderByWithAggregationInput | Prisma.ApplicationHistoryOrderByWithAggregationInput[]
  by: Prisma.ApplicationHistoryScalarFieldEnum[] | Prisma.ApplicationHistoryScalarFieldEnum
  having?: Prisma.ApplicationHistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ApplicationHistoryCountAggregateInputType | true
  _min?: ApplicationHistoryMinAggregateInputType
  _max?: ApplicationHistoryMaxAggregateInputType
}

export type ApplicationHistoryGroupByOutputType = {
  id: string
  applicationId: string
  previousStatusId: string | null
  newStatusId: string
  changedById: string | null
  changedAt: Date
  _count: ApplicationHistoryCountAggregateOutputType | null
  _min: ApplicationHistoryMinAggregateOutputType | null
  _max: ApplicationHistoryMaxAggregateOutputType | null
}

export type GetApplicationHistoryGroupByPayload<T extends ApplicationHistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ApplicationHistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ApplicationHistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ApplicationHistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ApplicationHistoryGroupByOutputType[P]>
      }
    >
  >



export type ApplicationHistoryWhereInput = {
  AND?: Prisma.ApplicationHistoryWhereInput | Prisma.ApplicationHistoryWhereInput[]
  OR?: Prisma.ApplicationHistoryWhereInput[]
  NOT?: Prisma.ApplicationHistoryWhereInput | Prisma.ApplicationHistoryWhereInput[]
  id?: Prisma.UuidFilter<"ApplicationHistory"> | string
  applicationId?: Prisma.UuidFilter<"ApplicationHistory"> | string
  previousStatusId?: Prisma.UuidNullableFilter<"ApplicationHistory"> | string | null
  newStatusId?: Prisma.UuidFilter<"ApplicationHistory"> | string
  changedById?: Prisma.UuidNullableFilter<"ApplicationHistory"> | string | null
  changedAt?: Prisma.DateTimeFilter<"ApplicationHistory"> | Date | string
  application?: Prisma.XOR<Prisma.VacancyApplicationScalarRelationFilter, Prisma.VacancyApplicationWhereInput>
  previousStatus?: Prisma.XOR<Prisma.ApplicationStatusNullableScalarRelationFilter, Prisma.ApplicationStatusWhereInput> | null
  newStatus?: Prisma.XOR<Prisma.ApplicationStatusScalarRelationFilter, Prisma.ApplicationStatusWhereInput>
  changedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type ApplicationHistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  previousStatusId?: Prisma.SortOrderInput | Prisma.SortOrder
  newStatusId?: Prisma.SortOrder
  changedById?: Prisma.SortOrderInput | Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  application?: Prisma.VacancyApplicationOrderByWithRelationInput
  previousStatus?: Prisma.ApplicationStatusOrderByWithRelationInput
  newStatus?: Prisma.ApplicationStatusOrderByWithRelationInput
  changedBy?: Prisma.UserOrderByWithRelationInput
}

export type ApplicationHistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ApplicationHistoryWhereInput | Prisma.ApplicationHistoryWhereInput[]
  OR?: Prisma.ApplicationHistoryWhereInput[]
  NOT?: Prisma.ApplicationHistoryWhereInput | Prisma.ApplicationHistoryWhereInput[]
  applicationId?: Prisma.UuidFilter<"ApplicationHistory"> | string
  previousStatusId?: Prisma.UuidNullableFilter<"ApplicationHistory"> | string | null
  newStatusId?: Prisma.UuidFilter<"ApplicationHistory"> | string
  changedById?: Prisma.UuidNullableFilter<"ApplicationHistory"> | string | null
  changedAt?: Prisma.DateTimeFilter<"ApplicationHistory"> | Date | string
  application?: Prisma.XOR<Prisma.VacancyApplicationScalarRelationFilter, Prisma.VacancyApplicationWhereInput>
  previousStatus?: Prisma.XOR<Prisma.ApplicationStatusNullableScalarRelationFilter, Prisma.ApplicationStatusWhereInput> | null
  newStatus?: Prisma.XOR<Prisma.ApplicationStatusScalarRelationFilter, Prisma.ApplicationStatusWhereInput>
  changedBy?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type ApplicationHistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  previousStatusId?: Prisma.SortOrderInput | Prisma.SortOrder
  newStatusId?: Prisma.SortOrder
  changedById?: Prisma.SortOrderInput | Prisma.SortOrder
  changedAt?: Prisma.SortOrder
  _count?: Prisma.ApplicationHistoryCountOrderByAggregateInput
  _max?: Prisma.ApplicationHistoryMaxOrderByAggregateInput
  _min?: Prisma.ApplicationHistoryMinOrderByAggregateInput
}

export type ApplicationHistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.ApplicationHistoryScalarWhereWithAggregatesInput | Prisma.ApplicationHistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.ApplicationHistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ApplicationHistoryScalarWhereWithAggregatesInput | Prisma.ApplicationHistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"ApplicationHistory"> | string
  applicationId?: Prisma.UuidWithAggregatesFilter<"ApplicationHistory"> | string
  previousStatusId?: Prisma.UuidNullableWithAggregatesFilter<"ApplicationHistory"> | string | null
  newStatusId?: Prisma.UuidWithAggregatesFilter<"ApplicationHistory"> | string
  changedById?: Prisma.UuidNullableWithAggregatesFilter<"ApplicationHistory"> | string | null
  changedAt?: Prisma.DateTimeWithAggregatesFilter<"ApplicationHistory"> | Date | string
}

export type ApplicationHistoryCreateInput = {
  id?: string
  changedAt?: Date | string
  application: Prisma.VacancyApplicationCreateNestedOneWithoutHistoryInput
  previousStatus?: Prisma.ApplicationStatusCreateNestedOneWithoutPreviousChangesInput
  newStatus: Prisma.ApplicationStatusCreateNestedOneWithoutNewChangesInput
  changedBy?: Prisma.UserCreateNestedOneWithoutApplicationChangesInput
}

export type ApplicationHistoryUncheckedCreateInput = {
  id?: string
  applicationId: string
  previousStatusId?: string | null
  newStatusId: string
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.VacancyApplicationUpdateOneRequiredWithoutHistoryNestedInput
  previousStatus?: Prisma.ApplicationStatusUpdateOneWithoutPreviousChangesNestedInput
  newStatus?: Prisma.ApplicationStatusUpdateOneRequiredWithoutNewChangesNestedInput
  changedBy?: Prisma.UserUpdateOneWithoutApplicationChangesNestedInput
}

export type ApplicationHistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryCreateManyInput = {
  id?: string
  applicationId: string
  previousStatusId?: string | null
  newStatusId: string
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryListRelationFilter = {
  every?: Prisma.ApplicationHistoryWhereInput
  some?: Prisma.ApplicationHistoryWhereInput
  none?: Prisma.ApplicationHistoryWhereInput
}

export type ApplicationHistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ApplicationHistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  previousStatusId?: Prisma.SortOrder
  newStatusId?: Prisma.SortOrder
  changedById?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
}

export type ApplicationHistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  previousStatusId?: Prisma.SortOrder
  newStatusId?: Prisma.SortOrder
  changedById?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
}

export type ApplicationHistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  applicationId?: Prisma.SortOrder
  previousStatusId?: Prisma.SortOrder
  newStatusId?: Prisma.SortOrder
  changedById?: Prisma.SortOrder
  changedAt?: Prisma.SortOrder
}

export type ApplicationHistoryCreateNestedManyWithoutChangedByInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput> | Prisma.ApplicationHistoryCreateWithoutChangedByInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput | Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyChangedByInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUncheckedCreateNestedManyWithoutChangedByInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput> | Prisma.ApplicationHistoryCreateWithoutChangedByInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput | Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyChangedByInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUpdateManyWithoutChangedByNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput> | Prisma.ApplicationHistoryCreateWithoutChangedByInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput | Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutChangedByInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutChangedByInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyChangedByInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutChangedByInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutChangedByInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutChangedByInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutChangedByInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryUncheckedUpdateManyWithoutChangedByNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput> | Prisma.ApplicationHistoryCreateWithoutChangedByInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput | Prisma.ApplicationHistoryCreateOrConnectWithoutChangedByInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutChangedByInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutChangedByInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyChangedByInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutChangedByInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutChangedByInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutChangedByInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutChangedByInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryCreateNestedManyWithoutPreviousStatusInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput> | Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyPreviousStatusInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryCreateNestedManyWithoutNewStatusInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput> | Prisma.ApplicationHistoryCreateWithoutNewStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyNewStatusInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUncheckedCreateNestedManyWithoutPreviousStatusInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput> | Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyPreviousStatusInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUncheckedCreateNestedManyWithoutNewStatusInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput> | Prisma.ApplicationHistoryCreateWithoutNewStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyNewStatusInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUpdateManyWithoutPreviousStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput> | Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutPreviousStatusInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutPreviousStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyPreviousStatusInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutPreviousStatusInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutPreviousStatusInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutPreviousStatusInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutPreviousStatusInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryUpdateManyWithoutNewStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput> | Prisma.ApplicationHistoryCreateWithoutNewStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutNewStatusInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutNewStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyNewStatusInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutNewStatusInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutNewStatusInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutNewStatusInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutNewStatusInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryUncheckedUpdateManyWithoutPreviousStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput> | Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutPreviousStatusInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutPreviousStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyPreviousStatusInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutPreviousStatusInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutPreviousStatusInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutPreviousStatusInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutPreviousStatusInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryUncheckedUpdateManyWithoutNewStatusNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput> | Prisma.ApplicationHistoryCreateWithoutNewStatusInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput | Prisma.ApplicationHistoryCreateOrConnectWithoutNewStatusInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutNewStatusInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutNewStatusInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyNewStatusInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutNewStatusInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutNewStatusInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutNewStatusInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutNewStatusInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryCreateNestedManyWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationHistoryCreateWithoutApplicationInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput | Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyApplicationInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUncheckedCreateNestedManyWithoutApplicationInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationHistoryCreateWithoutApplicationInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput | Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyApplicationInputEnvelope
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
}

export type ApplicationHistoryUpdateManyWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationHistoryCreateWithoutApplicationInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput | Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutApplicationInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyApplicationInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutApplicationInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutApplicationInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutApplicationInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryUncheckedUpdateManyWithoutApplicationNestedInput = {
  create?: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput> | Prisma.ApplicationHistoryCreateWithoutApplicationInput[] | Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput[]
  connectOrCreate?: Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput | Prisma.ApplicationHistoryCreateOrConnectWithoutApplicationInput[]
  upsert?: Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationHistoryUpsertWithWhereUniqueWithoutApplicationInput[]
  createMany?: Prisma.ApplicationHistoryCreateManyApplicationInputEnvelope
  set?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  disconnect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  delete?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  connect?: Prisma.ApplicationHistoryWhereUniqueInput | Prisma.ApplicationHistoryWhereUniqueInput[]
  update?: Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutApplicationInput | Prisma.ApplicationHistoryUpdateWithWhereUniqueWithoutApplicationInput[]
  updateMany?: Prisma.ApplicationHistoryUpdateManyWithWhereWithoutApplicationInput | Prisma.ApplicationHistoryUpdateManyWithWhereWithoutApplicationInput[]
  deleteMany?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
}

export type ApplicationHistoryCreateWithoutChangedByInput = {
  id?: string
  changedAt?: Date | string
  application: Prisma.VacancyApplicationCreateNestedOneWithoutHistoryInput
  previousStatus?: Prisma.ApplicationStatusCreateNestedOneWithoutPreviousChangesInput
  newStatus: Prisma.ApplicationStatusCreateNestedOneWithoutNewChangesInput
}

export type ApplicationHistoryUncheckedCreateWithoutChangedByInput = {
  id?: string
  applicationId: string
  previousStatusId?: string | null
  newStatusId: string
  changedAt?: Date | string
}

export type ApplicationHistoryCreateOrConnectWithoutChangedByInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput>
}

export type ApplicationHistoryCreateManyChangedByInputEnvelope = {
  data: Prisma.ApplicationHistoryCreateManyChangedByInput | Prisma.ApplicationHistoryCreateManyChangedByInput[]
  skipDuplicates?: boolean
}

export type ApplicationHistoryUpsertWithWhereUniqueWithoutChangedByInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutChangedByInput>
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedCreateWithoutChangedByInput>
}

export type ApplicationHistoryUpdateWithWhereUniqueWithoutChangedByInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutChangedByInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutChangedByInput>
}

export type ApplicationHistoryUpdateManyWithWhereWithoutChangedByInput = {
  where: Prisma.ApplicationHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateManyMutationInput, Prisma.ApplicationHistoryUncheckedUpdateManyWithoutChangedByInput>
}

export type ApplicationHistoryScalarWhereInput = {
  AND?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
  OR?: Prisma.ApplicationHistoryScalarWhereInput[]
  NOT?: Prisma.ApplicationHistoryScalarWhereInput | Prisma.ApplicationHistoryScalarWhereInput[]
  id?: Prisma.UuidFilter<"ApplicationHistory"> | string
  applicationId?: Prisma.UuidFilter<"ApplicationHistory"> | string
  previousStatusId?: Prisma.UuidNullableFilter<"ApplicationHistory"> | string | null
  newStatusId?: Prisma.UuidFilter<"ApplicationHistory"> | string
  changedById?: Prisma.UuidNullableFilter<"ApplicationHistory"> | string | null
  changedAt?: Prisma.DateTimeFilter<"ApplicationHistory"> | Date | string
}

export type ApplicationHistoryCreateWithoutPreviousStatusInput = {
  id?: string
  changedAt?: Date | string
  application: Prisma.VacancyApplicationCreateNestedOneWithoutHistoryInput
  newStatus: Prisma.ApplicationStatusCreateNestedOneWithoutNewChangesInput
  changedBy?: Prisma.UserCreateNestedOneWithoutApplicationChangesInput
}

export type ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput = {
  id?: string
  applicationId: string
  newStatusId: string
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryCreateOrConnectWithoutPreviousStatusInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput>
}

export type ApplicationHistoryCreateManyPreviousStatusInputEnvelope = {
  data: Prisma.ApplicationHistoryCreateManyPreviousStatusInput | Prisma.ApplicationHistoryCreateManyPreviousStatusInput[]
  skipDuplicates?: boolean
}

export type ApplicationHistoryCreateWithoutNewStatusInput = {
  id?: string
  changedAt?: Date | string
  application: Prisma.VacancyApplicationCreateNestedOneWithoutHistoryInput
  previousStatus?: Prisma.ApplicationStatusCreateNestedOneWithoutPreviousChangesInput
  changedBy?: Prisma.UserCreateNestedOneWithoutApplicationChangesInput
}

export type ApplicationHistoryUncheckedCreateWithoutNewStatusInput = {
  id?: string
  applicationId: string
  previousStatusId?: string | null
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryCreateOrConnectWithoutNewStatusInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput>
}

export type ApplicationHistoryCreateManyNewStatusInputEnvelope = {
  data: Prisma.ApplicationHistoryCreateManyNewStatusInput | Prisma.ApplicationHistoryCreateManyNewStatusInput[]
  skipDuplicates?: boolean
}

export type ApplicationHistoryUpsertWithWhereUniqueWithoutPreviousStatusInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutPreviousStatusInput>
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutPreviousStatusInput>
}

export type ApplicationHistoryUpdateWithWhereUniqueWithoutPreviousStatusInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutPreviousStatusInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutPreviousStatusInput>
}

export type ApplicationHistoryUpdateManyWithWhereWithoutPreviousStatusInput = {
  where: Prisma.ApplicationHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateManyMutationInput, Prisma.ApplicationHistoryUncheckedUpdateManyWithoutPreviousStatusInput>
}

export type ApplicationHistoryUpsertWithWhereUniqueWithoutNewStatusInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutNewStatusInput>
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedCreateWithoutNewStatusInput>
}

export type ApplicationHistoryUpdateWithWhereUniqueWithoutNewStatusInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutNewStatusInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutNewStatusInput>
}

export type ApplicationHistoryUpdateManyWithWhereWithoutNewStatusInput = {
  where: Prisma.ApplicationHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateManyMutationInput, Prisma.ApplicationHistoryUncheckedUpdateManyWithoutNewStatusInput>
}

export type ApplicationHistoryCreateWithoutApplicationInput = {
  id?: string
  changedAt?: Date | string
  previousStatus?: Prisma.ApplicationStatusCreateNestedOneWithoutPreviousChangesInput
  newStatus: Prisma.ApplicationStatusCreateNestedOneWithoutNewChangesInput
  changedBy?: Prisma.UserCreateNestedOneWithoutApplicationChangesInput
}

export type ApplicationHistoryUncheckedCreateWithoutApplicationInput = {
  id?: string
  previousStatusId?: string | null
  newStatusId: string
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryCreateOrConnectWithoutApplicationInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput>
}

export type ApplicationHistoryCreateManyApplicationInputEnvelope = {
  data: Prisma.ApplicationHistoryCreateManyApplicationInput | Prisma.ApplicationHistoryCreateManyApplicationInput[]
  skipDuplicates?: boolean
}

export type ApplicationHistoryUpsertWithWhereUniqueWithoutApplicationInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutApplicationInput>
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedCreateWithoutApplicationInput>
}

export type ApplicationHistoryUpdateWithWhereUniqueWithoutApplicationInput = {
  where: Prisma.ApplicationHistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateWithoutApplicationInput, Prisma.ApplicationHistoryUncheckedUpdateWithoutApplicationInput>
}

export type ApplicationHistoryUpdateManyWithWhereWithoutApplicationInput = {
  where: Prisma.ApplicationHistoryScalarWhereInput
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateManyMutationInput, Prisma.ApplicationHistoryUncheckedUpdateManyWithoutApplicationInput>
}

export type ApplicationHistoryCreateManyChangedByInput = {
  id?: string
  applicationId: string
  previousStatusId?: string | null
  newStatusId: string
  changedAt?: Date | string
}

export type ApplicationHistoryUpdateWithoutChangedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.VacancyApplicationUpdateOneRequiredWithoutHistoryNestedInput
  previousStatus?: Prisma.ApplicationStatusUpdateOneWithoutPreviousChangesNestedInput
  newStatus?: Prisma.ApplicationStatusUpdateOneRequiredWithoutNewChangesNestedInput
}

export type ApplicationHistoryUncheckedUpdateWithoutChangedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryUncheckedUpdateManyWithoutChangedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryCreateManyPreviousStatusInput = {
  id?: string
  applicationId: string
  newStatusId: string
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryCreateManyNewStatusInput = {
  id?: string
  applicationId: string
  previousStatusId?: string | null
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryUpdateWithoutPreviousStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.VacancyApplicationUpdateOneRequiredWithoutHistoryNestedInput
  newStatus?: Prisma.ApplicationStatusUpdateOneRequiredWithoutNewChangesNestedInput
  changedBy?: Prisma.UserUpdateOneWithoutApplicationChangesNestedInput
}

export type ApplicationHistoryUncheckedUpdateWithoutPreviousStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryUncheckedUpdateManyWithoutPreviousStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryUpdateWithoutNewStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  application?: Prisma.VacancyApplicationUpdateOneRequiredWithoutHistoryNestedInput
  previousStatus?: Prisma.ApplicationStatusUpdateOneWithoutPreviousChangesNestedInput
  changedBy?: Prisma.UserUpdateOneWithoutApplicationChangesNestedInput
}

export type ApplicationHistoryUncheckedUpdateWithoutNewStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryUncheckedUpdateManyWithoutNewStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  applicationId?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryCreateManyApplicationInput = {
  id?: string
  previousStatusId?: string | null
  newStatusId: string
  changedById?: string | null
  changedAt?: Date | string
}

export type ApplicationHistoryUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  previousStatus?: Prisma.ApplicationStatusUpdateOneWithoutPreviousChangesNestedInput
  newStatus?: Prisma.ApplicationStatusUpdateOneRequiredWithoutNewChangesNestedInput
  changedBy?: Prisma.UserUpdateOneWithoutApplicationChangesNestedInput
}

export type ApplicationHistoryUncheckedUpdateWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ApplicationHistoryUncheckedUpdateManyWithoutApplicationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  previousStatusId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newStatusId?: Prisma.StringFieldUpdateOperationsInput | string
  changedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ApplicationHistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  previousStatusId?: boolean
  newStatusId?: boolean
  changedById?: boolean
  changedAt?: boolean
  application?: boolean | Prisma.VacancyApplicationDefaultArgs<ExtArgs>
  previousStatus?: boolean | Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>
  newStatus?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  changedBy?: boolean | Prisma.ApplicationHistory$changedByArgs<ExtArgs>
}, ExtArgs["result"]["applicationHistory"]>

export type ApplicationHistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  previousStatusId?: boolean
  newStatusId?: boolean
  changedById?: boolean
  changedAt?: boolean
  application?: boolean | Prisma.VacancyApplicationDefaultArgs<ExtArgs>
  previousStatus?: boolean | Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>
  newStatus?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  changedBy?: boolean | Prisma.ApplicationHistory$changedByArgs<ExtArgs>
}, ExtArgs["result"]["applicationHistory"]>

export type ApplicationHistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  applicationId?: boolean
  previousStatusId?: boolean
  newStatusId?: boolean
  changedById?: boolean
  changedAt?: boolean
  application?: boolean | Prisma.VacancyApplicationDefaultArgs<ExtArgs>
  previousStatus?: boolean | Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>
  newStatus?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  changedBy?: boolean | Prisma.ApplicationHistory$changedByArgs<ExtArgs>
}, ExtArgs["result"]["applicationHistory"]>

export type ApplicationHistorySelectScalar = {
  id?: boolean
  applicationId?: boolean
  previousStatusId?: boolean
  newStatusId?: boolean
  changedById?: boolean
  changedAt?: boolean
}

export type ApplicationHistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "applicationId" | "previousStatusId" | "newStatusId" | "changedById" | "changedAt", ExtArgs["result"]["applicationHistory"]>
export type ApplicationHistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.VacancyApplicationDefaultArgs<ExtArgs>
  previousStatus?: boolean | Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>
  newStatus?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  changedBy?: boolean | Prisma.ApplicationHistory$changedByArgs<ExtArgs>
}
export type ApplicationHistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.VacancyApplicationDefaultArgs<ExtArgs>
  previousStatus?: boolean | Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>
  newStatus?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  changedBy?: boolean | Prisma.ApplicationHistory$changedByArgs<ExtArgs>
}
export type ApplicationHistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  application?: boolean | Prisma.VacancyApplicationDefaultArgs<ExtArgs>
  previousStatus?: boolean | Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>
  newStatus?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  changedBy?: boolean | Prisma.ApplicationHistory$changedByArgs<ExtArgs>
}

export type $ApplicationHistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ApplicationHistory"
  objects: {
    application: Prisma.$VacancyApplicationPayload<ExtArgs>
    previousStatus: Prisma.$ApplicationStatusPayload<ExtArgs> | null
    newStatus: Prisma.$ApplicationStatusPayload<ExtArgs>
    changedBy: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    applicationId: string
    previousStatusId: string | null
    newStatusId: string
    changedById: string | null
    changedAt: Date
  }, ExtArgs["result"]["applicationHistory"]>
  composites: {}
}

export type ApplicationHistoryGetPayload<S extends boolean | null | undefined | ApplicationHistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload, S>

export type ApplicationHistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ApplicationHistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ApplicationHistoryCountAggregateInputType | true
  }

export interface ApplicationHistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ApplicationHistory'], meta: { name: 'ApplicationHistory' } }
  /**
   * Find zero or one ApplicationHistory that matches the filter.
   * @param {ApplicationHistoryFindUniqueArgs} args - Arguments to find a ApplicationHistory
   * @example
   * // Get one ApplicationHistory
   * const applicationHistory = await prisma.applicationHistory.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ApplicationHistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ApplicationHistory that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ApplicationHistoryFindUniqueOrThrowArgs} args - Arguments to find a ApplicationHistory
   * @example
   * // Get one ApplicationHistory
   * const applicationHistory = await prisma.applicationHistory.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ApplicationHistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationHistory that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryFindFirstArgs} args - Arguments to find a ApplicationHistory
   * @example
   * // Get one ApplicationHistory
   * const applicationHistory = await prisma.applicationHistory.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ApplicationHistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, ApplicationHistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ApplicationHistory that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryFindFirstOrThrowArgs} args - Arguments to find a ApplicationHistory
   * @example
   * // Get one ApplicationHistory
   * const applicationHistory = await prisma.applicationHistory.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ApplicationHistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ApplicationHistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ApplicationHistories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ApplicationHistories
   * const applicationHistories = await prisma.applicationHistory.findMany()
   * 
   * // Get first 10 ApplicationHistories
   * const applicationHistories = await prisma.applicationHistory.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const applicationHistoryWithIdOnly = await prisma.applicationHistory.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ApplicationHistoryFindManyArgs>(args?: Prisma.SelectSubset<T, ApplicationHistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ApplicationHistory.
   * @param {ApplicationHistoryCreateArgs} args - Arguments to create a ApplicationHistory.
   * @example
   * // Create one ApplicationHistory
   * const ApplicationHistory = await prisma.applicationHistory.create({
   *   data: {
   *     // ... data to create a ApplicationHistory
   *   }
   * })
   * 
   */
  create<T extends ApplicationHistoryCreateArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryCreateArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ApplicationHistories.
   * @param {ApplicationHistoryCreateManyArgs} args - Arguments to create many ApplicationHistories.
   * @example
   * // Create many ApplicationHistories
   * const applicationHistory = await prisma.applicationHistory.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ApplicationHistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, ApplicationHistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ApplicationHistories and returns the data saved in the database.
   * @param {ApplicationHistoryCreateManyAndReturnArgs} args - Arguments to create many ApplicationHistories.
   * @example
   * // Create many ApplicationHistories
   * const applicationHistory = await prisma.applicationHistory.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ApplicationHistories and only return the `id`
   * const applicationHistoryWithIdOnly = await prisma.applicationHistory.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ApplicationHistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ApplicationHistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ApplicationHistory.
   * @param {ApplicationHistoryDeleteArgs} args - Arguments to delete one ApplicationHistory.
   * @example
   * // Delete one ApplicationHistory
   * const ApplicationHistory = await prisma.applicationHistory.delete({
   *   where: {
   *     // ... filter to delete one ApplicationHistory
   *   }
   * })
   * 
   */
  delete<T extends ApplicationHistoryDeleteArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ApplicationHistory.
   * @param {ApplicationHistoryUpdateArgs} args - Arguments to update one ApplicationHistory.
   * @example
   * // Update one ApplicationHistory
   * const applicationHistory = await prisma.applicationHistory.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ApplicationHistoryUpdateArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ApplicationHistories.
   * @param {ApplicationHistoryDeleteManyArgs} args - Arguments to filter ApplicationHistories to delete.
   * @example
   * // Delete a few ApplicationHistories
   * const { count } = await prisma.applicationHistory.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ApplicationHistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, ApplicationHistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ApplicationHistories
   * const applicationHistory = await prisma.applicationHistory.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ApplicationHistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ApplicationHistories and returns the data updated in the database.
   * @param {ApplicationHistoryUpdateManyAndReturnArgs} args - Arguments to update many ApplicationHistories.
   * @example
   * // Update many ApplicationHistories
   * const applicationHistory = await prisma.applicationHistory.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ApplicationHistories and only return the `id`
   * const applicationHistoryWithIdOnly = await prisma.applicationHistory.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ApplicationHistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ApplicationHistory.
   * @param {ApplicationHistoryUpsertArgs} args - Arguments to update or create a ApplicationHistory.
   * @example
   * // Update or create a ApplicationHistory
   * const applicationHistory = await prisma.applicationHistory.upsert({
   *   create: {
   *     // ... data to create a ApplicationHistory
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ApplicationHistory we want to update
   *   }
   * })
   */
  upsert<T extends ApplicationHistoryUpsertArgs>(args: Prisma.SelectSubset<T, ApplicationHistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__ApplicationHistoryClient<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ApplicationHistories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryCountArgs} args - Arguments to filter ApplicationHistories to count.
   * @example
   * // Count the number of ApplicationHistories
   * const count = await prisma.applicationHistory.count({
   *   where: {
   *     // ... the filter for the ApplicationHistories we want to count
   *   }
   * })
  **/
  count<T extends ApplicationHistoryCountArgs>(
    args?: Prisma.Subset<T, ApplicationHistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ApplicationHistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ApplicationHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ApplicationHistoryAggregateArgs>(args: Prisma.Subset<T, ApplicationHistoryAggregateArgs>): Prisma.PrismaPromise<GetApplicationHistoryAggregateType<T>>

  /**
   * Group by ApplicationHistory.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ApplicationHistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ApplicationHistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ApplicationHistoryGroupByArgs['orderBy'] }
      : { orderBy?: ApplicationHistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ApplicationHistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetApplicationHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ApplicationHistory model
 */
readonly fields: ApplicationHistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ApplicationHistory.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ApplicationHistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  application<T extends Prisma.VacancyApplicationDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VacancyApplicationDefaultArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  previousStatus<T extends Prisma.ApplicationHistory$previousStatusArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApplicationHistory$previousStatusArgs<ExtArgs>>): Prisma.Prisma__ApplicationStatusClient<runtime.Types.Result.GetResult<Prisma.$ApplicationStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  newStatus<T extends Prisma.ApplicationStatusDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApplicationStatusDefaultArgs<ExtArgs>>): Prisma.Prisma__ApplicationStatusClient<runtime.Types.Result.GetResult<Prisma.$ApplicationStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  changedBy<T extends Prisma.ApplicationHistory$changedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApplicationHistory$changedByArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ApplicationHistory model
 */
export interface ApplicationHistoryFieldRefs {
  readonly id: Prisma.FieldRef<"ApplicationHistory", 'String'>
  readonly applicationId: Prisma.FieldRef<"ApplicationHistory", 'String'>
  readonly previousStatusId: Prisma.FieldRef<"ApplicationHistory", 'String'>
  readonly newStatusId: Prisma.FieldRef<"ApplicationHistory", 'String'>
  readonly changedById: Prisma.FieldRef<"ApplicationHistory", 'String'>
  readonly changedAt: Prisma.FieldRef<"ApplicationHistory", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ApplicationHistory findUnique
 */
export type ApplicationHistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationHistory to fetch.
   */
  where: Prisma.ApplicationHistoryWhereUniqueInput
}

/**
 * ApplicationHistory findUniqueOrThrow
 */
export type ApplicationHistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationHistory to fetch.
   */
  where: Prisma.ApplicationHistoryWhereUniqueInput
}

/**
 * ApplicationHistory findFirst
 */
export type ApplicationHistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationHistory to fetch.
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationHistories to fetch.
   */
  orderBy?: Prisma.ApplicationHistoryOrderByWithRelationInput | Prisma.ApplicationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationHistories.
   */
  cursor?: Prisma.ApplicationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationHistories.
   */
  distinct?: Prisma.ApplicationHistoryScalarFieldEnum | Prisma.ApplicationHistoryScalarFieldEnum[]
}

/**
 * ApplicationHistory findFirstOrThrow
 */
export type ApplicationHistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationHistory to fetch.
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationHistories to fetch.
   */
  orderBy?: Prisma.ApplicationHistoryOrderByWithRelationInput | Prisma.ApplicationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ApplicationHistories.
   */
  cursor?: Prisma.ApplicationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationHistories.
   */
  distinct?: Prisma.ApplicationHistoryScalarFieldEnum | Prisma.ApplicationHistoryScalarFieldEnum[]
}

/**
 * ApplicationHistory findMany
 */
export type ApplicationHistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * Filter, which ApplicationHistories to fetch.
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ApplicationHistories to fetch.
   */
  orderBy?: Prisma.ApplicationHistoryOrderByWithRelationInput | Prisma.ApplicationHistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ApplicationHistories.
   */
  cursor?: Prisma.ApplicationHistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ApplicationHistories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ApplicationHistories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ApplicationHistories.
   */
  distinct?: Prisma.ApplicationHistoryScalarFieldEnum | Prisma.ApplicationHistoryScalarFieldEnum[]
}

/**
 * ApplicationHistory create
 */
export type ApplicationHistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a ApplicationHistory.
   */
  data: Prisma.XOR<Prisma.ApplicationHistoryCreateInput, Prisma.ApplicationHistoryUncheckedCreateInput>
}

/**
 * ApplicationHistory createMany
 */
export type ApplicationHistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ApplicationHistories.
   */
  data: Prisma.ApplicationHistoryCreateManyInput | Prisma.ApplicationHistoryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ApplicationHistory createManyAndReturn
 */
export type ApplicationHistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * The data used to create many ApplicationHistories.
   */
  data: Prisma.ApplicationHistoryCreateManyInput | Prisma.ApplicationHistoryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ApplicationHistory update
 */
export type ApplicationHistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a ApplicationHistory.
   */
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateInput, Prisma.ApplicationHistoryUncheckedUpdateInput>
  /**
   * Choose, which ApplicationHistory to update.
   */
  where: Prisma.ApplicationHistoryWhereUniqueInput
}

/**
 * ApplicationHistory updateMany
 */
export type ApplicationHistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ApplicationHistories.
   */
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateManyMutationInput, Prisma.ApplicationHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationHistories to update
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * Limit how many ApplicationHistories to update.
   */
  limit?: number
}

/**
 * ApplicationHistory updateManyAndReturn
 */
export type ApplicationHistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * The data used to update ApplicationHistories.
   */
  data: Prisma.XOR<Prisma.ApplicationHistoryUpdateManyMutationInput, Prisma.ApplicationHistoryUncheckedUpdateManyInput>
  /**
   * Filter which ApplicationHistories to update
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * Limit how many ApplicationHistories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ApplicationHistory upsert
 */
export type ApplicationHistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the ApplicationHistory to update in case it exists.
   */
  where: Prisma.ApplicationHistoryWhereUniqueInput
  /**
   * In case the ApplicationHistory found by the `where` argument doesn't exist, create a new ApplicationHistory with this data.
   */
  create: Prisma.XOR<Prisma.ApplicationHistoryCreateInput, Prisma.ApplicationHistoryUncheckedCreateInput>
  /**
   * In case the ApplicationHistory was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ApplicationHistoryUpdateInput, Prisma.ApplicationHistoryUncheckedUpdateInput>
}

/**
 * ApplicationHistory delete
 */
export type ApplicationHistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  /**
   * Filter which ApplicationHistory to delete.
   */
  where: Prisma.ApplicationHistoryWhereUniqueInput
}

/**
 * ApplicationHistory deleteMany
 */
export type ApplicationHistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ApplicationHistories to delete
   */
  where?: Prisma.ApplicationHistoryWhereInput
  /**
   * Limit how many ApplicationHistories to delete.
   */
  limit?: number
}

/**
 * ApplicationHistory.previousStatus
 */
export type ApplicationHistory$previousStatusArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationStatus
   */
  select?: Prisma.ApplicationStatusSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationStatus
   */
  omit?: Prisma.ApplicationStatusOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationStatusInclude<ExtArgs> | null
  where?: Prisma.ApplicationStatusWhereInput
}

/**
 * ApplicationHistory.changedBy
 */
export type ApplicationHistory$changedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * ApplicationHistory without action
 */
export type ApplicationHistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
}
