
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JobOfferContractType` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model JobOfferContractType
 * 
 */
export type JobOfferContractTypeModel = runtime.Types.Result.DefaultSelection<Prisma.$JobOfferContractTypePayload>

export type AggregateJobOfferContractType = {
  _count: JobOfferContractTypeCountAggregateOutputType | null
  _min: JobOfferContractTypeMinAggregateOutputType | null
  _max: JobOfferContractTypeMaxAggregateOutputType | null
}

export type JobOfferContractTypeMinAggregateOutputType = {
  id: string | null
  title: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JobOfferContractTypeMaxAggregateOutputType = {
  id: string | null
  title: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JobOfferContractTypeCountAggregateOutputType = {
  id: number
  title: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type JobOfferContractTypeMinAggregateInputType = {
  id?: true
  title?: true
  createdAt?: true
  updatedAt?: true
}

export type JobOfferContractTypeMaxAggregateInputType = {
  id?: true
  title?: true
  createdAt?: true
  updatedAt?: true
}

export type JobOfferContractTypeCountAggregateInputType = {
  id?: true
  title?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type JobOfferContractTypeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JobOfferContractType to aggregate.
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobOfferContractTypes to fetch.
   */
  orderBy?: Prisma.JobOfferContractTypeOrderByWithRelationInput | Prisma.JobOfferContractTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JobOfferContractTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobOfferContractTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobOfferContractTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JobOfferContractTypes
  **/
  _count?: true | JobOfferContractTypeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JobOfferContractTypeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JobOfferContractTypeMaxAggregateInputType
}

export type GetJobOfferContractTypeAggregateType<T extends JobOfferContractTypeAggregateArgs> = {
      [P in keyof T & keyof AggregateJobOfferContractType]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJobOfferContractType[P]>
    : Prisma.GetScalarType<T[P], AggregateJobOfferContractType[P]>
}




export type JobOfferContractTypeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JobOfferContractTypeWhereInput
  orderBy?: Prisma.JobOfferContractTypeOrderByWithAggregationInput | Prisma.JobOfferContractTypeOrderByWithAggregationInput[]
  by: Prisma.JobOfferContractTypeScalarFieldEnum[] | Prisma.JobOfferContractTypeScalarFieldEnum
  having?: Prisma.JobOfferContractTypeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JobOfferContractTypeCountAggregateInputType | true
  _min?: JobOfferContractTypeMinAggregateInputType
  _max?: JobOfferContractTypeMaxAggregateInputType
}

export type JobOfferContractTypeGroupByOutputType = {
  id: string
  title: string
  createdAt: Date
  updatedAt: Date
  _count: JobOfferContractTypeCountAggregateOutputType | null
  _min: JobOfferContractTypeMinAggregateOutputType | null
  _max: JobOfferContractTypeMaxAggregateOutputType | null
}

export type GetJobOfferContractTypeGroupByPayload<T extends JobOfferContractTypeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JobOfferContractTypeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JobOfferContractTypeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JobOfferContractTypeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JobOfferContractTypeGroupByOutputType[P]>
      }
    >
  >



export type JobOfferContractTypeWhereInput = {
  AND?: Prisma.JobOfferContractTypeWhereInput | Prisma.JobOfferContractTypeWhereInput[]
  OR?: Prisma.JobOfferContractTypeWhereInput[]
  NOT?: Prisma.JobOfferContractTypeWhereInput | Prisma.JobOfferContractTypeWhereInput[]
  id?: Prisma.UuidFilter<"JobOfferContractType"> | string
  title?: Prisma.StringFilter<"JobOfferContractType"> | string
  createdAt?: Prisma.DateTimeFilter<"JobOfferContractType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JobOfferContractType"> | Date | string
  jobOffers?: Prisma.JobOfferListRelationFilter
}

export type JobOfferContractTypeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  jobOffers?: Prisma.JobOfferOrderByRelationAggregateInput
}

export type JobOfferContractTypeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  title?: string
  AND?: Prisma.JobOfferContractTypeWhereInput | Prisma.JobOfferContractTypeWhereInput[]
  OR?: Prisma.JobOfferContractTypeWhereInput[]
  NOT?: Prisma.JobOfferContractTypeWhereInput | Prisma.JobOfferContractTypeWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"JobOfferContractType"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JobOfferContractType"> | Date | string
  jobOffers?: Prisma.JobOfferListRelationFilter
}, "id" | "title">

export type JobOfferContractTypeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.JobOfferContractTypeCountOrderByAggregateInput
  _max?: Prisma.JobOfferContractTypeMaxOrderByAggregateInput
  _min?: Prisma.JobOfferContractTypeMinOrderByAggregateInput
}

export type JobOfferContractTypeScalarWhereWithAggregatesInput = {
  AND?: Prisma.JobOfferContractTypeScalarWhereWithAggregatesInput | Prisma.JobOfferContractTypeScalarWhereWithAggregatesInput[]
  OR?: Prisma.JobOfferContractTypeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JobOfferContractTypeScalarWhereWithAggregatesInput | Prisma.JobOfferContractTypeScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"JobOfferContractType"> | string
  title?: Prisma.StringWithAggregatesFilter<"JobOfferContractType"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"JobOfferContractType"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"JobOfferContractType"> | Date | string
}

export type JobOfferContractTypeCreateInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  jobOffers?: Prisma.JobOfferCreateNestedManyWithoutContractTypeInput
}

export type JobOfferContractTypeUncheckedCreateInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
  jobOffers?: Prisma.JobOfferUncheckedCreateNestedManyWithoutContractTypeInput
}

export type JobOfferContractTypeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jobOffers?: Prisma.JobOfferUpdateManyWithoutContractTypeNestedInput
}

export type JobOfferContractTypeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  jobOffers?: Prisma.JobOfferUncheckedUpdateManyWithoutContractTypeNestedInput
}

export type JobOfferContractTypeCreateManyInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobOfferContractTypeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobOfferContractTypeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobOfferContractTypeScalarRelationFilter = {
  is?: Prisma.JobOfferContractTypeWhereInput
  isNot?: Prisma.JobOfferContractTypeWhereInput
}

export type JobOfferContractTypeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JobOfferContractTypeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JobOfferContractTypeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JobOfferContractTypeCreateNestedOneWithoutJobOffersInput = {
  create?: Prisma.XOR<Prisma.JobOfferContractTypeCreateWithoutJobOffersInput, Prisma.JobOfferContractTypeUncheckedCreateWithoutJobOffersInput>
  connectOrCreate?: Prisma.JobOfferContractTypeCreateOrConnectWithoutJobOffersInput
  connect?: Prisma.JobOfferContractTypeWhereUniqueInput
}

export type JobOfferContractTypeUpdateOneRequiredWithoutJobOffersNestedInput = {
  create?: Prisma.XOR<Prisma.JobOfferContractTypeCreateWithoutJobOffersInput, Prisma.JobOfferContractTypeUncheckedCreateWithoutJobOffersInput>
  connectOrCreate?: Prisma.JobOfferContractTypeCreateOrConnectWithoutJobOffersInput
  upsert?: Prisma.JobOfferContractTypeUpsertWithoutJobOffersInput
  connect?: Prisma.JobOfferContractTypeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.JobOfferContractTypeUpdateToOneWithWhereWithoutJobOffersInput, Prisma.JobOfferContractTypeUpdateWithoutJobOffersInput>, Prisma.JobOfferContractTypeUncheckedUpdateWithoutJobOffersInput>
}

export type JobOfferContractTypeCreateWithoutJobOffersInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobOfferContractTypeUncheckedCreateWithoutJobOffersInput = {
  id?: string
  title: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JobOfferContractTypeCreateOrConnectWithoutJobOffersInput = {
  where: Prisma.JobOfferContractTypeWhereUniqueInput
  create: Prisma.XOR<Prisma.JobOfferContractTypeCreateWithoutJobOffersInput, Prisma.JobOfferContractTypeUncheckedCreateWithoutJobOffersInput>
}

export type JobOfferContractTypeUpsertWithoutJobOffersInput = {
  update: Prisma.XOR<Prisma.JobOfferContractTypeUpdateWithoutJobOffersInput, Prisma.JobOfferContractTypeUncheckedUpdateWithoutJobOffersInput>
  create: Prisma.XOR<Prisma.JobOfferContractTypeCreateWithoutJobOffersInput, Prisma.JobOfferContractTypeUncheckedCreateWithoutJobOffersInput>
  where?: Prisma.JobOfferContractTypeWhereInput
}

export type JobOfferContractTypeUpdateToOneWithWhereWithoutJobOffersInput = {
  where?: Prisma.JobOfferContractTypeWhereInput
  data: Prisma.XOR<Prisma.JobOfferContractTypeUpdateWithoutJobOffersInput, Prisma.JobOfferContractTypeUncheckedUpdateWithoutJobOffersInput>
}

export type JobOfferContractTypeUpdateWithoutJobOffersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JobOfferContractTypeUncheckedUpdateWithoutJobOffersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type JobOfferContractTypeCountOutputType
 */

export type JobOfferContractTypeCountOutputType = {
  jobOffers: number
}

export type JobOfferContractTypeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobOffers?: boolean | JobOfferContractTypeCountOutputTypeCountJobOffersArgs
}

/**
 * JobOfferContractTypeCountOutputType without action
 */
export type JobOfferContractTypeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractTypeCountOutputType
   */
  select?: Prisma.JobOfferContractTypeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * JobOfferContractTypeCountOutputType without action
 */
export type JobOfferContractTypeCountOutputTypeCountJobOffersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JobOfferWhereInput
}


export type JobOfferContractTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  jobOffers?: boolean | Prisma.JobOfferContractType$jobOffersArgs<ExtArgs>
  _count?: boolean | Prisma.JobOfferContractTypeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["jobOfferContractType"]>

export type JobOfferContractTypeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["jobOfferContractType"]>

export type JobOfferContractTypeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["jobOfferContractType"]>

export type JobOfferContractTypeSelectScalar = {
  id?: boolean
  title?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type JobOfferContractTypeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "title" | "createdAt" | "updatedAt", ExtArgs["result"]["jobOfferContractType"]>
export type JobOfferContractTypeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  jobOffers?: boolean | Prisma.JobOfferContractType$jobOffersArgs<ExtArgs>
  _count?: boolean | Prisma.JobOfferContractTypeCountOutputTypeDefaultArgs<ExtArgs>
}
export type JobOfferContractTypeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type JobOfferContractTypeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $JobOfferContractTypePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JobOfferContractType"
  objects: {
    jobOffers: Prisma.$JobOfferPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    title: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["jobOfferContractType"]>
  composites: {}
}

export type JobOfferContractTypeGetPayload<S extends boolean | null | undefined | JobOfferContractTypeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload, S>

export type JobOfferContractTypeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JobOfferContractTypeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JobOfferContractTypeCountAggregateInputType | true
  }

export interface JobOfferContractTypeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JobOfferContractType'], meta: { name: 'JobOfferContractType' } }
  /**
   * Find zero or one JobOfferContractType that matches the filter.
   * @param {JobOfferContractTypeFindUniqueArgs} args - Arguments to find a JobOfferContractType
   * @example
   * // Get one JobOfferContractType
   * const jobOfferContractType = await prisma.jobOfferContractType.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JobOfferContractTypeFindUniqueArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JobOfferContractType that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JobOfferContractTypeFindUniqueOrThrowArgs} args - Arguments to find a JobOfferContractType
   * @example
   * // Get one JobOfferContractType
   * const jobOfferContractType = await prisma.jobOfferContractType.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JobOfferContractTypeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JobOfferContractType that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeFindFirstArgs} args - Arguments to find a JobOfferContractType
   * @example
   * // Get one JobOfferContractType
   * const jobOfferContractType = await prisma.jobOfferContractType.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JobOfferContractTypeFindFirstArgs>(args?: Prisma.SelectSubset<T, JobOfferContractTypeFindFirstArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JobOfferContractType that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeFindFirstOrThrowArgs} args - Arguments to find a JobOfferContractType
   * @example
   * // Get one JobOfferContractType
   * const jobOfferContractType = await prisma.jobOfferContractType.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JobOfferContractTypeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JobOfferContractTypeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JobOfferContractTypes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JobOfferContractTypes
   * const jobOfferContractTypes = await prisma.jobOfferContractType.findMany()
   * 
   * // Get first 10 JobOfferContractTypes
   * const jobOfferContractTypes = await prisma.jobOfferContractType.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const jobOfferContractTypeWithIdOnly = await prisma.jobOfferContractType.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JobOfferContractTypeFindManyArgs>(args?: Prisma.SelectSubset<T, JobOfferContractTypeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JobOfferContractType.
   * @param {JobOfferContractTypeCreateArgs} args - Arguments to create a JobOfferContractType.
   * @example
   * // Create one JobOfferContractType
   * const JobOfferContractType = await prisma.jobOfferContractType.create({
   *   data: {
   *     // ... data to create a JobOfferContractType
   *   }
   * })
   * 
   */
  create<T extends JobOfferContractTypeCreateArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeCreateArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JobOfferContractTypes.
   * @param {JobOfferContractTypeCreateManyArgs} args - Arguments to create many JobOfferContractTypes.
   * @example
   * // Create many JobOfferContractTypes
   * const jobOfferContractType = await prisma.jobOfferContractType.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JobOfferContractTypeCreateManyArgs>(args?: Prisma.SelectSubset<T, JobOfferContractTypeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JobOfferContractTypes and returns the data saved in the database.
   * @param {JobOfferContractTypeCreateManyAndReturnArgs} args - Arguments to create many JobOfferContractTypes.
   * @example
   * // Create many JobOfferContractTypes
   * const jobOfferContractType = await prisma.jobOfferContractType.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JobOfferContractTypes and only return the `id`
   * const jobOfferContractTypeWithIdOnly = await prisma.jobOfferContractType.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JobOfferContractTypeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JobOfferContractTypeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JobOfferContractType.
   * @param {JobOfferContractTypeDeleteArgs} args - Arguments to delete one JobOfferContractType.
   * @example
   * // Delete one JobOfferContractType
   * const JobOfferContractType = await prisma.jobOfferContractType.delete({
   *   where: {
   *     // ... filter to delete one JobOfferContractType
   *   }
   * })
   * 
   */
  delete<T extends JobOfferContractTypeDeleteArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeDeleteArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JobOfferContractType.
   * @param {JobOfferContractTypeUpdateArgs} args - Arguments to update one JobOfferContractType.
   * @example
   * // Update one JobOfferContractType
   * const jobOfferContractType = await prisma.jobOfferContractType.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JobOfferContractTypeUpdateArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeUpdateArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JobOfferContractTypes.
   * @param {JobOfferContractTypeDeleteManyArgs} args - Arguments to filter JobOfferContractTypes to delete.
   * @example
   * // Delete a few JobOfferContractTypes
   * const { count } = await prisma.jobOfferContractType.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JobOfferContractTypeDeleteManyArgs>(args?: Prisma.SelectSubset<T, JobOfferContractTypeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JobOfferContractTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JobOfferContractTypes
   * const jobOfferContractType = await prisma.jobOfferContractType.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JobOfferContractTypeUpdateManyArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JobOfferContractTypes and returns the data updated in the database.
   * @param {JobOfferContractTypeUpdateManyAndReturnArgs} args - Arguments to update many JobOfferContractTypes.
   * @example
   * // Update many JobOfferContractTypes
   * const jobOfferContractType = await prisma.jobOfferContractType.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JobOfferContractTypes and only return the `id`
   * const jobOfferContractTypeWithIdOnly = await prisma.jobOfferContractType.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JobOfferContractTypeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JobOfferContractType.
   * @param {JobOfferContractTypeUpsertArgs} args - Arguments to update or create a JobOfferContractType.
   * @example
   * // Update or create a JobOfferContractType
   * const jobOfferContractType = await prisma.jobOfferContractType.upsert({
   *   create: {
   *     // ... data to create a JobOfferContractType
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JobOfferContractType we want to update
   *   }
   * })
   */
  upsert<T extends JobOfferContractTypeUpsertArgs>(args: Prisma.SelectSubset<T, JobOfferContractTypeUpsertArgs<ExtArgs>>): Prisma.Prisma__JobOfferContractTypeClient<runtime.Types.Result.GetResult<Prisma.$JobOfferContractTypePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JobOfferContractTypes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeCountArgs} args - Arguments to filter JobOfferContractTypes to count.
   * @example
   * // Count the number of JobOfferContractTypes
   * const count = await prisma.jobOfferContractType.count({
   *   where: {
   *     // ... the filter for the JobOfferContractTypes we want to count
   *   }
   * })
  **/
  count<T extends JobOfferContractTypeCountArgs>(
    args?: Prisma.Subset<T, JobOfferContractTypeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JobOfferContractTypeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JobOfferContractType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JobOfferContractTypeAggregateArgs>(args: Prisma.Subset<T, JobOfferContractTypeAggregateArgs>): Prisma.PrismaPromise<GetJobOfferContractTypeAggregateType<T>>

  /**
   * Group by JobOfferContractType.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JobOfferContractTypeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JobOfferContractTypeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JobOfferContractTypeGroupByArgs['orderBy'] }
      : { orderBy?: JobOfferContractTypeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JobOfferContractTypeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJobOfferContractTypeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JobOfferContractType model
 */
readonly fields: JobOfferContractTypeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JobOfferContractType.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JobOfferContractTypeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  jobOffers<T extends Prisma.JobOfferContractType$jobOffersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.JobOfferContractType$jobOffersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JobOfferPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JobOfferContractType model
 */
export interface JobOfferContractTypeFieldRefs {
  readonly id: Prisma.FieldRef<"JobOfferContractType", 'String'>
  readonly title: Prisma.FieldRef<"JobOfferContractType", 'String'>
  readonly createdAt: Prisma.FieldRef<"JobOfferContractType", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"JobOfferContractType", 'DateTime'>
}
    

// Custom InputTypes
/**
 * JobOfferContractType findUnique
 */
export type JobOfferContractTypeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * Filter, which JobOfferContractType to fetch.
   */
  where: Prisma.JobOfferContractTypeWhereUniqueInput
}

/**
 * JobOfferContractType findUniqueOrThrow
 */
export type JobOfferContractTypeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * Filter, which JobOfferContractType to fetch.
   */
  where: Prisma.JobOfferContractTypeWhereUniqueInput
}

/**
 * JobOfferContractType findFirst
 */
export type JobOfferContractTypeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * Filter, which JobOfferContractType to fetch.
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobOfferContractTypes to fetch.
   */
  orderBy?: Prisma.JobOfferContractTypeOrderByWithRelationInput | Prisma.JobOfferContractTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JobOfferContractTypes.
   */
  cursor?: Prisma.JobOfferContractTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobOfferContractTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobOfferContractTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobOfferContractTypes.
   */
  distinct?: Prisma.JobOfferContractTypeScalarFieldEnum | Prisma.JobOfferContractTypeScalarFieldEnum[]
}

/**
 * JobOfferContractType findFirstOrThrow
 */
export type JobOfferContractTypeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * Filter, which JobOfferContractType to fetch.
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobOfferContractTypes to fetch.
   */
  orderBy?: Prisma.JobOfferContractTypeOrderByWithRelationInput | Prisma.JobOfferContractTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JobOfferContractTypes.
   */
  cursor?: Prisma.JobOfferContractTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobOfferContractTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobOfferContractTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobOfferContractTypes.
   */
  distinct?: Prisma.JobOfferContractTypeScalarFieldEnum | Prisma.JobOfferContractTypeScalarFieldEnum[]
}

/**
 * JobOfferContractType findMany
 */
export type JobOfferContractTypeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * Filter, which JobOfferContractTypes to fetch.
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JobOfferContractTypes to fetch.
   */
  orderBy?: Prisma.JobOfferContractTypeOrderByWithRelationInput | Prisma.JobOfferContractTypeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JobOfferContractTypes.
   */
  cursor?: Prisma.JobOfferContractTypeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JobOfferContractTypes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JobOfferContractTypes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JobOfferContractTypes.
   */
  distinct?: Prisma.JobOfferContractTypeScalarFieldEnum | Prisma.JobOfferContractTypeScalarFieldEnum[]
}

/**
 * JobOfferContractType create
 */
export type JobOfferContractTypeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * The data needed to create a JobOfferContractType.
   */
  data: Prisma.XOR<Prisma.JobOfferContractTypeCreateInput, Prisma.JobOfferContractTypeUncheckedCreateInput>
}

/**
 * JobOfferContractType createMany
 */
export type JobOfferContractTypeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JobOfferContractTypes.
   */
  data: Prisma.JobOfferContractTypeCreateManyInput | Prisma.JobOfferContractTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JobOfferContractType createManyAndReturn
 */
export type JobOfferContractTypeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * The data used to create many JobOfferContractTypes.
   */
  data: Prisma.JobOfferContractTypeCreateManyInput | Prisma.JobOfferContractTypeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JobOfferContractType update
 */
export type JobOfferContractTypeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * The data needed to update a JobOfferContractType.
   */
  data: Prisma.XOR<Prisma.JobOfferContractTypeUpdateInput, Prisma.JobOfferContractTypeUncheckedUpdateInput>
  /**
   * Choose, which JobOfferContractType to update.
   */
  where: Prisma.JobOfferContractTypeWhereUniqueInput
}

/**
 * JobOfferContractType updateMany
 */
export type JobOfferContractTypeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JobOfferContractTypes.
   */
  data: Prisma.XOR<Prisma.JobOfferContractTypeUpdateManyMutationInput, Prisma.JobOfferContractTypeUncheckedUpdateManyInput>
  /**
   * Filter which JobOfferContractTypes to update
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * Limit how many JobOfferContractTypes to update.
   */
  limit?: number
}

/**
 * JobOfferContractType updateManyAndReturn
 */
export type JobOfferContractTypeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * The data used to update JobOfferContractTypes.
   */
  data: Prisma.XOR<Prisma.JobOfferContractTypeUpdateManyMutationInput, Prisma.JobOfferContractTypeUncheckedUpdateManyInput>
  /**
   * Filter which JobOfferContractTypes to update
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * Limit how many JobOfferContractTypes to update.
   */
  limit?: number
}

/**
 * JobOfferContractType upsert
 */
export type JobOfferContractTypeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * The filter to search for the JobOfferContractType to update in case it exists.
   */
  where: Prisma.JobOfferContractTypeWhereUniqueInput
  /**
   * In case the JobOfferContractType found by the `where` argument doesn't exist, create a new JobOfferContractType with this data.
   */
  create: Prisma.XOR<Prisma.JobOfferContractTypeCreateInput, Prisma.JobOfferContractTypeUncheckedCreateInput>
  /**
   * In case the JobOfferContractType was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JobOfferContractTypeUpdateInput, Prisma.JobOfferContractTypeUncheckedUpdateInput>
}

/**
 * JobOfferContractType delete
 */
export type JobOfferContractTypeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
  /**
   * Filter which JobOfferContractType to delete.
   */
  where: Prisma.JobOfferContractTypeWhereUniqueInput
}

/**
 * JobOfferContractType deleteMany
 */
export type JobOfferContractTypeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JobOfferContractTypes to delete
   */
  where?: Prisma.JobOfferContractTypeWhereInput
  /**
   * Limit how many JobOfferContractTypes to delete.
   */
  limit?: number
}

/**
 * JobOfferContractType.jobOffers
 */
export type JobOfferContractType$jobOffersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOffer
   */
  select?: Prisma.JobOfferSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOffer
   */
  omit?: Prisma.JobOfferOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferInclude<ExtArgs> | null
  where?: Prisma.JobOfferWhereInput
  orderBy?: Prisma.JobOfferOrderByWithRelationInput | Prisma.JobOfferOrderByWithRelationInput[]
  cursor?: Prisma.JobOfferWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.JobOfferScalarFieldEnum | Prisma.JobOfferScalarFieldEnum[]
}

/**
 * JobOfferContractType without action
 */
export type JobOfferContractTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JobOfferContractType
   */
  select?: Prisma.JobOfferContractTypeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JobOfferContractType
   */
  omit?: Prisma.JobOfferContractTypeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.JobOfferContractTypeInclude<ExtArgs> | null
}
