
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SavedVacancy` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model SavedVacancy
 * 
 */
export type SavedVacancyModel = runtime.Types.Result.DefaultSelection<Prisma.$SavedVacancyPayload>

export type AggregateSavedVacancy = {
  _count: SavedVacancyCountAggregateOutputType | null
  _min: SavedVacancyMinAggregateOutputType | null
  _max: SavedVacancyMaxAggregateOutputType | null
}

export type SavedVacancyMinAggregateOutputType = {
  id: string | null
  userId: string | null
  vacancyId: string | null
  createdAt: Date | null
}

export type SavedVacancyMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  vacancyId: string | null
  createdAt: Date | null
}

export type SavedVacancyCountAggregateOutputType = {
  id: number
  userId: number
  vacancyId: number
  createdAt: number
  _all: number
}


export type SavedVacancyMinAggregateInputType = {
  id?: true
  userId?: true
  vacancyId?: true
  createdAt?: true
}

export type SavedVacancyMaxAggregateInputType = {
  id?: true
  userId?: true
  vacancyId?: true
  createdAt?: true
}

export type SavedVacancyCountAggregateInputType = {
  id?: true
  userId?: true
  vacancyId?: true
  createdAt?: true
  _all?: true
}

export type SavedVacancyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SavedVacancy to aggregate.
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedVacancies to fetch.
   */
  orderBy?: Prisma.SavedVacancyOrderByWithRelationInput | Prisma.SavedVacancyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SavedVacancyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedVacancies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedVacancies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SavedVacancies
  **/
  _count?: true | SavedVacancyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SavedVacancyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SavedVacancyMaxAggregateInputType
}

export type GetSavedVacancyAggregateType<T extends SavedVacancyAggregateArgs> = {
      [P in keyof T & keyof AggregateSavedVacancy]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSavedVacancy[P]>
    : Prisma.GetScalarType<T[P], AggregateSavedVacancy[P]>
}




export type SavedVacancyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SavedVacancyWhereInput
  orderBy?: Prisma.SavedVacancyOrderByWithAggregationInput | Prisma.SavedVacancyOrderByWithAggregationInput[]
  by: Prisma.SavedVacancyScalarFieldEnum[] | Prisma.SavedVacancyScalarFieldEnum
  having?: Prisma.SavedVacancyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SavedVacancyCountAggregateInputType | true
  _min?: SavedVacancyMinAggregateInputType
  _max?: SavedVacancyMaxAggregateInputType
}

export type SavedVacancyGroupByOutputType = {
  id: string
  userId: string
  vacancyId: string
  createdAt: Date
  _count: SavedVacancyCountAggregateOutputType | null
  _min: SavedVacancyMinAggregateOutputType | null
  _max: SavedVacancyMaxAggregateOutputType | null
}

export type GetSavedVacancyGroupByPayload<T extends SavedVacancyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SavedVacancyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SavedVacancyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SavedVacancyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SavedVacancyGroupByOutputType[P]>
      }
    >
  >



export type SavedVacancyWhereInput = {
  AND?: Prisma.SavedVacancyWhereInput | Prisma.SavedVacancyWhereInput[]
  OR?: Prisma.SavedVacancyWhereInput[]
  NOT?: Prisma.SavedVacancyWhereInput | Prisma.SavedVacancyWhereInput[]
  id?: Prisma.UuidFilter<"SavedVacancy"> | string
  userId?: Prisma.UuidFilter<"SavedVacancy"> | string
  vacancyId?: Prisma.UuidFilter<"SavedVacancy"> | string
  createdAt?: Prisma.DateTimeFilter<"SavedVacancy"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  vacancy?: Prisma.XOR<Prisma.VacancyScalarRelationFilter, Prisma.VacancyWhereInput>
}

export type SavedVacancyOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  vacancy?: Prisma.VacancyOrderByWithRelationInput
}

export type SavedVacancyWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_vacancyId?: Prisma.SavedVacancyUserIdVacancyIdCompoundUniqueInput
  AND?: Prisma.SavedVacancyWhereInput | Prisma.SavedVacancyWhereInput[]
  OR?: Prisma.SavedVacancyWhereInput[]
  NOT?: Prisma.SavedVacancyWhereInput | Prisma.SavedVacancyWhereInput[]
  userId?: Prisma.UuidFilter<"SavedVacancy"> | string
  vacancyId?: Prisma.UuidFilter<"SavedVacancy"> | string
  createdAt?: Prisma.DateTimeFilter<"SavedVacancy"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  vacancy?: Prisma.XOR<Prisma.VacancyScalarRelationFilter, Prisma.VacancyWhereInput>
}, "id" | "userId_vacancyId">

export type SavedVacancyOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.SavedVacancyCountOrderByAggregateInput
  _max?: Prisma.SavedVacancyMaxOrderByAggregateInput
  _min?: Prisma.SavedVacancyMinOrderByAggregateInput
}

export type SavedVacancyScalarWhereWithAggregatesInput = {
  AND?: Prisma.SavedVacancyScalarWhereWithAggregatesInput | Prisma.SavedVacancyScalarWhereWithAggregatesInput[]
  OR?: Prisma.SavedVacancyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SavedVacancyScalarWhereWithAggregatesInput | Prisma.SavedVacancyScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"SavedVacancy"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"SavedVacancy"> | string
  vacancyId?: Prisma.UuidWithAggregatesFilter<"SavedVacancy"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SavedVacancy"> | Date | string
}

export type SavedVacancyCreateInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSavedVacanciesInput
  vacancy: Prisma.VacancyCreateNestedOneWithoutSavedByInput
}

export type SavedVacancyUncheckedCreateInput = {
  id?: string
  userId: string
  vacancyId: string
  createdAt?: Date | string
}

export type SavedVacancyUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSavedVacanciesNestedInput
  vacancy?: Prisma.VacancyUpdateOneRequiredWithoutSavedByNestedInput
}

export type SavedVacancyUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedVacancyCreateManyInput = {
  id?: string
  userId: string
  vacancyId: string
  createdAt?: Date | string
}

export type SavedVacancyUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedVacancyUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedVacancyListRelationFilter = {
  every?: Prisma.SavedVacancyWhereInput
  some?: Prisma.SavedVacancyWhereInput
  none?: Prisma.SavedVacancyWhereInput
}

export type SavedVacancyOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SavedVacancyUserIdVacancyIdCompoundUniqueInput = {
  userId: string
  vacancyId: string
}

export type SavedVacancyCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SavedVacancyMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SavedVacancyMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type SavedVacancyCreateNestedManyWithoutVacancyInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutVacancyInput, Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput> | Prisma.SavedVacancyCreateWithoutVacancyInput[] | Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput | Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput[]
  createMany?: Prisma.SavedVacancyCreateManyVacancyInputEnvelope
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
}

export type SavedVacancyUncheckedCreateNestedManyWithoutVacancyInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutVacancyInput, Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput> | Prisma.SavedVacancyCreateWithoutVacancyInput[] | Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput | Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput[]
  createMany?: Prisma.SavedVacancyCreateManyVacancyInputEnvelope
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
}

export type SavedVacancyUpdateManyWithoutVacancyNestedInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutVacancyInput, Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput> | Prisma.SavedVacancyCreateWithoutVacancyInput[] | Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput | Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput[]
  upsert?: Prisma.SavedVacancyUpsertWithWhereUniqueWithoutVacancyInput | Prisma.SavedVacancyUpsertWithWhereUniqueWithoutVacancyInput[]
  createMany?: Prisma.SavedVacancyCreateManyVacancyInputEnvelope
  set?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  disconnect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  delete?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  update?: Prisma.SavedVacancyUpdateWithWhereUniqueWithoutVacancyInput | Prisma.SavedVacancyUpdateWithWhereUniqueWithoutVacancyInput[]
  updateMany?: Prisma.SavedVacancyUpdateManyWithWhereWithoutVacancyInput | Prisma.SavedVacancyUpdateManyWithWhereWithoutVacancyInput[]
  deleteMany?: Prisma.SavedVacancyScalarWhereInput | Prisma.SavedVacancyScalarWhereInput[]
}

export type SavedVacancyUncheckedUpdateManyWithoutVacancyNestedInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutVacancyInput, Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput> | Prisma.SavedVacancyCreateWithoutVacancyInput[] | Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput | Prisma.SavedVacancyCreateOrConnectWithoutVacancyInput[]
  upsert?: Prisma.SavedVacancyUpsertWithWhereUniqueWithoutVacancyInput | Prisma.SavedVacancyUpsertWithWhereUniqueWithoutVacancyInput[]
  createMany?: Prisma.SavedVacancyCreateManyVacancyInputEnvelope
  set?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  disconnect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  delete?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  update?: Prisma.SavedVacancyUpdateWithWhereUniqueWithoutVacancyInput | Prisma.SavedVacancyUpdateWithWhereUniqueWithoutVacancyInput[]
  updateMany?: Prisma.SavedVacancyUpdateManyWithWhereWithoutVacancyInput | Prisma.SavedVacancyUpdateManyWithWhereWithoutVacancyInput[]
  deleteMany?: Prisma.SavedVacancyScalarWhereInput | Prisma.SavedVacancyScalarWhereInput[]
}

export type SavedVacancyCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutUserInput, Prisma.SavedVacancyUncheckedCreateWithoutUserInput> | Prisma.SavedVacancyCreateWithoutUserInput[] | Prisma.SavedVacancyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutUserInput | Prisma.SavedVacancyCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SavedVacancyCreateManyUserInputEnvelope
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
}

export type SavedVacancyUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutUserInput, Prisma.SavedVacancyUncheckedCreateWithoutUserInput> | Prisma.SavedVacancyCreateWithoutUserInput[] | Prisma.SavedVacancyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutUserInput | Prisma.SavedVacancyCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.SavedVacancyCreateManyUserInputEnvelope
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
}

export type SavedVacancyUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutUserInput, Prisma.SavedVacancyUncheckedCreateWithoutUserInput> | Prisma.SavedVacancyCreateWithoutUserInput[] | Prisma.SavedVacancyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutUserInput | Prisma.SavedVacancyCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SavedVacancyUpsertWithWhereUniqueWithoutUserInput | Prisma.SavedVacancyUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SavedVacancyCreateManyUserInputEnvelope
  set?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  disconnect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  delete?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  update?: Prisma.SavedVacancyUpdateWithWhereUniqueWithoutUserInput | Prisma.SavedVacancyUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SavedVacancyUpdateManyWithWhereWithoutUserInput | Prisma.SavedVacancyUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SavedVacancyScalarWhereInput | Prisma.SavedVacancyScalarWhereInput[]
}

export type SavedVacancyUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.SavedVacancyCreateWithoutUserInput, Prisma.SavedVacancyUncheckedCreateWithoutUserInput> | Prisma.SavedVacancyCreateWithoutUserInput[] | Prisma.SavedVacancyUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.SavedVacancyCreateOrConnectWithoutUserInput | Prisma.SavedVacancyCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.SavedVacancyUpsertWithWhereUniqueWithoutUserInput | Prisma.SavedVacancyUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.SavedVacancyCreateManyUserInputEnvelope
  set?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  disconnect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  delete?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  connect?: Prisma.SavedVacancyWhereUniqueInput | Prisma.SavedVacancyWhereUniqueInput[]
  update?: Prisma.SavedVacancyUpdateWithWhereUniqueWithoutUserInput | Prisma.SavedVacancyUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.SavedVacancyUpdateManyWithWhereWithoutUserInput | Prisma.SavedVacancyUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.SavedVacancyScalarWhereInput | Prisma.SavedVacancyScalarWhereInput[]
}

export type SavedVacancyCreateWithoutVacancyInput = {
  id?: string
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutSavedVacanciesInput
}

export type SavedVacancyUncheckedCreateWithoutVacancyInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type SavedVacancyCreateOrConnectWithoutVacancyInput = {
  where: Prisma.SavedVacancyWhereUniqueInput
  create: Prisma.XOR<Prisma.SavedVacancyCreateWithoutVacancyInput, Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput>
}

export type SavedVacancyCreateManyVacancyInputEnvelope = {
  data: Prisma.SavedVacancyCreateManyVacancyInput | Prisma.SavedVacancyCreateManyVacancyInput[]
  skipDuplicates?: boolean
}

export type SavedVacancyUpsertWithWhereUniqueWithoutVacancyInput = {
  where: Prisma.SavedVacancyWhereUniqueInput
  update: Prisma.XOR<Prisma.SavedVacancyUpdateWithoutVacancyInput, Prisma.SavedVacancyUncheckedUpdateWithoutVacancyInput>
  create: Prisma.XOR<Prisma.SavedVacancyCreateWithoutVacancyInput, Prisma.SavedVacancyUncheckedCreateWithoutVacancyInput>
}

export type SavedVacancyUpdateWithWhereUniqueWithoutVacancyInput = {
  where: Prisma.SavedVacancyWhereUniqueInput
  data: Prisma.XOR<Prisma.SavedVacancyUpdateWithoutVacancyInput, Prisma.SavedVacancyUncheckedUpdateWithoutVacancyInput>
}

export type SavedVacancyUpdateManyWithWhereWithoutVacancyInput = {
  where: Prisma.SavedVacancyScalarWhereInput
  data: Prisma.XOR<Prisma.SavedVacancyUpdateManyMutationInput, Prisma.SavedVacancyUncheckedUpdateManyWithoutVacancyInput>
}

export type SavedVacancyScalarWhereInput = {
  AND?: Prisma.SavedVacancyScalarWhereInput | Prisma.SavedVacancyScalarWhereInput[]
  OR?: Prisma.SavedVacancyScalarWhereInput[]
  NOT?: Prisma.SavedVacancyScalarWhereInput | Prisma.SavedVacancyScalarWhereInput[]
  id?: Prisma.UuidFilter<"SavedVacancy"> | string
  userId?: Prisma.UuidFilter<"SavedVacancy"> | string
  vacancyId?: Prisma.UuidFilter<"SavedVacancy"> | string
  createdAt?: Prisma.DateTimeFilter<"SavedVacancy"> | Date | string
}

export type SavedVacancyCreateWithoutUserInput = {
  id?: string
  createdAt?: Date | string
  vacancy: Prisma.VacancyCreateNestedOneWithoutSavedByInput
}

export type SavedVacancyUncheckedCreateWithoutUserInput = {
  id?: string
  vacancyId: string
  createdAt?: Date | string
}

export type SavedVacancyCreateOrConnectWithoutUserInput = {
  where: Prisma.SavedVacancyWhereUniqueInput
  create: Prisma.XOR<Prisma.SavedVacancyCreateWithoutUserInput, Prisma.SavedVacancyUncheckedCreateWithoutUserInput>
}

export type SavedVacancyCreateManyUserInputEnvelope = {
  data: Prisma.SavedVacancyCreateManyUserInput | Prisma.SavedVacancyCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type SavedVacancyUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.SavedVacancyWhereUniqueInput
  update: Prisma.XOR<Prisma.SavedVacancyUpdateWithoutUserInput, Prisma.SavedVacancyUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.SavedVacancyCreateWithoutUserInput, Prisma.SavedVacancyUncheckedCreateWithoutUserInput>
}

export type SavedVacancyUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.SavedVacancyWhereUniqueInput
  data: Prisma.XOR<Prisma.SavedVacancyUpdateWithoutUserInput, Prisma.SavedVacancyUncheckedUpdateWithoutUserInput>
}

export type SavedVacancyUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.SavedVacancyScalarWhereInput
  data: Prisma.XOR<Prisma.SavedVacancyUpdateManyMutationInput, Prisma.SavedVacancyUncheckedUpdateManyWithoutUserInput>
}

export type SavedVacancyCreateManyVacancyInput = {
  id?: string
  userId: string
  createdAt?: Date | string
}

export type SavedVacancyUpdateWithoutVacancyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutSavedVacanciesNestedInput
}

export type SavedVacancyUncheckedUpdateWithoutVacancyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedVacancyUncheckedUpdateManyWithoutVacancyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedVacancyCreateManyUserInput = {
  id?: string
  vacancyId: string
  createdAt?: Date | string
}

export type SavedVacancyUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vacancy?: Prisma.VacancyUpdateOneRequiredWithoutSavedByNestedInput
}

export type SavedVacancyUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SavedVacancyUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type SavedVacancySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  vacancyId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedVacancy"]>

export type SavedVacancySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  vacancyId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedVacancy"]>

export type SavedVacancySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  vacancyId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["savedVacancy"]>

export type SavedVacancySelectScalar = {
  id?: boolean
  userId?: boolean
  vacancyId?: boolean
  createdAt?: boolean
}

export type SavedVacancyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "vacancyId" | "createdAt", ExtArgs["result"]["savedVacancy"]>
export type SavedVacancyInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
}
export type SavedVacancyIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
}
export type SavedVacancyIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
}

export type $SavedVacancyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SavedVacancy"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    vacancy: Prisma.$VacancyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    vacancyId: string
    createdAt: Date
  }, ExtArgs["result"]["savedVacancy"]>
  composites: {}
}

export type SavedVacancyGetPayload<S extends boolean | null | undefined | SavedVacancyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload, S>

export type SavedVacancyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SavedVacancyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SavedVacancyCountAggregateInputType | true
  }

export interface SavedVacancyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SavedVacancy'], meta: { name: 'SavedVacancy' } }
  /**
   * Find zero or one SavedVacancy that matches the filter.
   * @param {SavedVacancyFindUniqueArgs} args - Arguments to find a SavedVacancy
   * @example
   * // Get one SavedVacancy
   * const savedVacancy = await prisma.savedVacancy.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SavedVacancyFindUniqueArgs>(args: Prisma.SelectSubset<T, SavedVacancyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SavedVacancy that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SavedVacancyFindUniqueOrThrowArgs} args - Arguments to find a SavedVacancy
   * @example
   * // Get one SavedVacancy
   * const savedVacancy = await prisma.savedVacancy.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SavedVacancyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SavedVacancyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SavedVacancy that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyFindFirstArgs} args - Arguments to find a SavedVacancy
   * @example
   * // Get one SavedVacancy
   * const savedVacancy = await prisma.savedVacancy.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SavedVacancyFindFirstArgs>(args?: Prisma.SelectSubset<T, SavedVacancyFindFirstArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SavedVacancy that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyFindFirstOrThrowArgs} args - Arguments to find a SavedVacancy
   * @example
   * // Get one SavedVacancy
   * const savedVacancy = await prisma.savedVacancy.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SavedVacancyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SavedVacancyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SavedVacancies that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SavedVacancies
   * const savedVacancies = await prisma.savedVacancy.findMany()
   * 
   * // Get first 10 SavedVacancies
   * const savedVacancies = await prisma.savedVacancy.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const savedVacancyWithIdOnly = await prisma.savedVacancy.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SavedVacancyFindManyArgs>(args?: Prisma.SelectSubset<T, SavedVacancyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SavedVacancy.
   * @param {SavedVacancyCreateArgs} args - Arguments to create a SavedVacancy.
   * @example
   * // Create one SavedVacancy
   * const SavedVacancy = await prisma.savedVacancy.create({
   *   data: {
   *     // ... data to create a SavedVacancy
   *   }
   * })
   * 
   */
  create<T extends SavedVacancyCreateArgs>(args: Prisma.SelectSubset<T, SavedVacancyCreateArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SavedVacancies.
   * @param {SavedVacancyCreateManyArgs} args - Arguments to create many SavedVacancies.
   * @example
   * // Create many SavedVacancies
   * const savedVacancy = await prisma.savedVacancy.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SavedVacancyCreateManyArgs>(args?: Prisma.SelectSubset<T, SavedVacancyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SavedVacancies and returns the data saved in the database.
   * @param {SavedVacancyCreateManyAndReturnArgs} args - Arguments to create many SavedVacancies.
   * @example
   * // Create many SavedVacancies
   * const savedVacancy = await prisma.savedVacancy.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SavedVacancies and only return the `id`
   * const savedVacancyWithIdOnly = await prisma.savedVacancy.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SavedVacancyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SavedVacancyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SavedVacancy.
   * @param {SavedVacancyDeleteArgs} args - Arguments to delete one SavedVacancy.
   * @example
   * // Delete one SavedVacancy
   * const SavedVacancy = await prisma.savedVacancy.delete({
   *   where: {
   *     // ... filter to delete one SavedVacancy
   *   }
   * })
   * 
   */
  delete<T extends SavedVacancyDeleteArgs>(args: Prisma.SelectSubset<T, SavedVacancyDeleteArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SavedVacancy.
   * @param {SavedVacancyUpdateArgs} args - Arguments to update one SavedVacancy.
   * @example
   * // Update one SavedVacancy
   * const savedVacancy = await prisma.savedVacancy.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SavedVacancyUpdateArgs>(args: Prisma.SelectSubset<T, SavedVacancyUpdateArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SavedVacancies.
   * @param {SavedVacancyDeleteManyArgs} args - Arguments to filter SavedVacancies to delete.
   * @example
   * // Delete a few SavedVacancies
   * const { count } = await prisma.savedVacancy.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SavedVacancyDeleteManyArgs>(args?: Prisma.SelectSubset<T, SavedVacancyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SavedVacancies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SavedVacancies
   * const savedVacancy = await prisma.savedVacancy.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SavedVacancyUpdateManyArgs>(args: Prisma.SelectSubset<T, SavedVacancyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SavedVacancies and returns the data updated in the database.
   * @param {SavedVacancyUpdateManyAndReturnArgs} args - Arguments to update many SavedVacancies.
   * @example
   * // Update many SavedVacancies
   * const savedVacancy = await prisma.savedVacancy.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SavedVacancies and only return the `id`
   * const savedVacancyWithIdOnly = await prisma.savedVacancy.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SavedVacancyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SavedVacancyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SavedVacancy.
   * @param {SavedVacancyUpsertArgs} args - Arguments to update or create a SavedVacancy.
   * @example
   * // Update or create a SavedVacancy
   * const savedVacancy = await prisma.savedVacancy.upsert({
   *   create: {
   *     // ... data to create a SavedVacancy
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SavedVacancy we want to update
   *   }
   * })
   */
  upsert<T extends SavedVacancyUpsertArgs>(args: Prisma.SelectSubset<T, SavedVacancyUpsertArgs<ExtArgs>>): Prisma.Prisma__SavedVacancyClient<runtime.Types.Result.GetResult<Prisma.$SavedVacancyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SavedVacancies.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyCountArgs} args - Arguments to filter SavedVacancies to count.
   * @example
   * // Count the number of SavedVacancies
   * const count = await prisma.savedVacancy.count({
   *   where: {
   *     // ... the filter for the SavedVacancies we want to count
   *   }
   * })
  **/
  count<T extends SavedVacancyCountArgs>(
    args?: Prisma.Subset<T, SavedVacancyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SavedVacancyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SavedVacancy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SavedVacancyAggregateArgs>(args: Prisma.Subset<T, SavedVacancyAggregateArgs>): Prisma.PrismaPromise<GetSavedVacancyAggregateType<T>>

  /**
   * Group by SavedVacancy.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SavedVacancyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SavedVacancyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SavedVacancyGroupByArgs['orderBy'] }
      : { orderBy?: SavedVacancyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SavedVacancyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSavedVacancyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SavedVacancy model
 */
readonly fields: SavedVacancyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SavedVacancy.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SavedVacancyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  vacancy<T extends Prisma.VacancyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VacancyDefaultArgs<ExtArgs>>): Prisma.Prisma__VacancyClient<runtime.Types.Result.GetResult<Prisma.$VacancyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SavedVacancy model
 */
export interface SavedVacancyFieldRefs {
  readonly id: Prisma.FieldRef<"SavedVacancy", 'String'>
  readonly userId: Prisma.FieldRef<"SavedVacancy", 'String'>
  readonly vacancyId: Prisma.FieldRef<"SavedVacancy", 'String'>
  readonly createdAt: Prisma.FieldRef<"SavedVacancy", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SavedVacancy findUnique
 */
export type SavedVacancyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * Filter, which SavedVacancy to fetch.
   */
  where: Prisma.SavedVacancyWhereUniqueInput
}

/**
 * SavedVacancy findUniqueOrThrow
 */
export type SavedVacancyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * Filter, which SavedVacancy to fetch.
   */
  where: Prisma.SavedVacancyWhereUniqueInput
}

/**
 * SavedVacancy findFirst
 */
export type SavedVacancyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * Filter, which SavedVacancy to fetch.
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedVacancies to fetch.
   */
  orderBy?: Prisma.SavedVacancyOrderByWithRelationInput | Prisma.SavedVacancyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SavedVacancies.
   */
  cursor?: Prisma.SavedVacancyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedVacancies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedVacancies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedVacancies.
   */
  distinct?: Prisma.SavedVacancyScalarFieldEnum | Prisma.SavedVacancyScalarFieldEnum[]
}

/**
 * SavedVacancy findFirstOrThrow
 */
export type SavedVacancyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * Filter, which SavedVacancy to fetch.
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedVacancies to fetch.
   */
  orderBy?: Prisma.SavedVacancyOrderByWithRelationInput | Prisma.SavedVacancyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SavedVacancies.
   */
  cursor?: Prisma.SavedVacancyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedVacancies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedVacancies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedVacancies.
   */
  distinct?: Prisma.SavedVacancyScalarFieldEnum | Prisma.SavedVacancyScalarFieldEnum[]
}

/**
 * SavedVacancy findMany
 */
export type SavedVacancyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * Filter, which SavedVacancies to fetch.
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SavedVacancies to fetch.
   */
  orderBy?: Prisma.SavedVacancyOrderByWithRelationInput | Prisma.SavedVacancyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SavedVacancies.
   */
  cursor?: Prisma.SavedVacancyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SavedVacancies from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SavedVacancies.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SavedVacancies.
   */
  distinct?: Prisma.SavedVacancyScalarFieldEnum | Prisma.SavedVacancyScalarFieldEnum[]
}

/**
 * SavedVacancy create
 */
export type SavedVacancyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * The data needed to create a SavedVacancy.
   */
  data: Prisma.XOR<Prisma.SavedVacancyCreateInput, Prisma.SavedVacancyUncheckedCreateInput>
}

/**
 * SavedVacancy createMany
 */
export type SavedVacancyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SavedVacancies.
   */
  data: Prisma.SavedVacancyCreateManyInput | Prisma.SavedVacancyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * SavedVacancy createManyAndReturn
 */
export type SavedVacancyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * The data used to create many SavedVacancies.
   */
  data: Prisma.SavedVacancyCreateManyInput | Prisma.SavedVacancyCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SavedVacancy update
 */
export type SavedVacancyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * The data needed to update a SavedVacancy.
   */
  data: Prisma.XOR<Prisma.SavedVacancyUpdateInput, Prisma.SavedVacancyUncheckedUpdateInput>
  /**
   * Choose, which SavedVacancy to update.
   */
  where: Prisma.SavedVacancyWhereUniqueInput
}

/**
 * SavedVacancy updateMany
 */
export type SavedVacancyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SavedVacancies.
   */
  data: Prisma.XOR<Prisma.SavedVacancyUpdateManyMutationInput, Prisma.SavedVacancyUncheckedUpdateManyInput>
  /**
   * Filter which SavedVacancies to update
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * Limit how many SavedVacancies to update.
   */
  limit?: number
}

/**
 * SavedVacancy updateManyAndReturn
 */
export type SavedVacancyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * The data used to update SavedVacancies.
   */
  data: Prisma.XOR<Prisma.SavedVacancyUpdateManyMutationInput, Prisma.SavedVacancyUncheckedUpdateManyInput>
  /**
   * Filter which SavedVacancies to update
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * Limit how many SavedVacancies to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SavedVacancy upsert
 */
export type SavedVacancyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * The filter to search for the SavedVacancy to update in case it exists.
   */
  where: Prisma.SavedVacancyWhereUniqueInput
  /**
   * In case the SavedVacancy found by the `where` argument doesn't exist, create a new SavedVacancy with this data.
   */
  create: Prisma.XOR<Prisma.SavedVacancyCreateInput, Prisma.SavedVacancyUncheckedCreateInput>
  /**
   * In case the SavedVacancy was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SavedVacancyUpdateInput, Prisma.SavedVacancyUncheckedUpdateInput>
}

/**
 * SavedVacancy delete
 */
export type SavedVacancyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
  /**
   * Filter which SavedVacancy to delete.
   */
  where: Prisma.SavedVacancyWhereUniqueInput
}

/**
 * SavedVacancy deleteMany
 */
export type SavedVacancyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SavedVacancies to delete
   */
  where?: Prisma.SavedVacancyWhereInput
  /**
   * Limit how many SavedVacancies to delete.
   */
  limit?: number
}

/**
 * SavedVacancy without action
 */
export type SavedVacancyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SavedVacancy
   */
  select?: Prisma.SavedVacancySelect<ExtArgs> | null
  /**
   * Omit specific fields from the SavedVacancy
   */
  omit?: Prisma.SavedVacancyOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SavedVacancyInclude<ExtArgs> | null
}
