
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `VacancyApplication` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model VacancyApplication
 * 
 */
export type VacancyApplicationModel = runtime.Types.Result.DefaultSelection<Prisma.$VacancyApplicationPayload>

export type AggregateVacancyApplication = {
  _count: VacancyApplicationCountAggregateOutputType | null
  _min: VacancyApplicationMinAggregateOutputType | null
  _max: VacancyApplicationMaxAggregateOutputType | null
}

export type VacancyApplicationMinAggregateOutputType = {
  id: string | null
  vacancyId: string | null
  userId: string | null
  statusId: string | null
  appliedAt: Date | null
  updatedAt: Date | null
}

export type VacancyApplicationMaxAggregateOutputType = {
  id: string | null
  vacancyId: string | null
  userId: string | null
  statusId: string | null
  appliedAt: Date | null
  updatedAt: Date | null
}

export type VacancyApplicationCountAggregateOutputType = {
  id: number
  vacancyId: number
  userId: number
  statusId: number
  appliedAt: number
  updatedAt: number
  _all: number
}


export type VacancyApplicationMinAggregateInputType = {
  id?: true
  vacancyId?: true
  userId?: true
  statusId?: true
  appliedAt?: true
  updatedAt?: true
}

export type VacancyApplicationMaxAggregateInputType = {
  id?: true
  vacancyId?: true
  userId?: true
  statusId?: true
  appliedAt?: true
  updatedAt?: true
}

export type VacancyApplicationCountAggregateInputType = {
  id?: true
  vacancyId?: true
  userId?: true
  statusId?: true
  appliedAt?: true
  updatedAt?: true
  _all?: true
}

export type VacancyApplicationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VacancyApplication to aggregate.
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VacancyApplications to fetch.
   */
  orderBy?: Prisma.VacancyApplicationOrderByWithRelationInput | Prisma.VacancyApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.VacancyApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VacancyApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VacancyApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned VacancyApplications
  **/
  _count?: true | VacancyApplicationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: VacancyApplicationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: VacancyApplicationMaxAggregateInputType
}

export type GetVacancyApplicationAggregateType<T extends VacancyApplicationAggregateArgs> = {
      [P in keyof T & keyof AggregateVacancyApplication]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVacancyApplication[P]>
    : Prisma.GetScalarType<T[P], AggregateVacancyApplication[P]>
}




export type VacancyApplicationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.VacancyApplicationWhereInput
  orderBy?: Prisma.VacancyApplicationOrderByWithAggregationInput | Prisma.VacancyApplicationOrderByWithAggregationInput[]
  by: Prisma.VacancyApplicationScalarFieldEnum[] | Prisma.VacancyApplicationScalarFieldEnum
  having?: Prisma.VacancyApplicationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: VacancyApplicationCountAggregateInputType | true
  _min?: VacancyApplicationMinAggregateInputType
  _max?: VacancyApplicationMaxAggregateInputType
}

export type VacancyApplicationGroupByOutputType = {
  id: string
  vacancyId: string
  userId: string
  statusId: string
  appliedAt: Date
  updatedAt: Date
  _count: VacancyApplicationCountAggregateOutputType | null
  _min: VacancyApplicationMinAggregateOutputType | null
  _max: VacancyApplicationMaxAggregateOutputType | null
}

export type GetVacancyApplicationGroupByPayload<T extends VacancyApplicationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<VacancyApplicationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof VacancyApplicationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], VacancyApplicationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], VacancyApplicationGroupByOutputType[P]>
      }
    >
  >



export type VacancyApplicationWhereInput = {
  AND?: Prisma.VacancyApplicationWhereInput | Prisma.VacancyApplicationWhereInput[]
  OR?: Prisma.VacancyApplicationWhereInput[]
  NOT?: Prisma.VacancyApplicationWhereInput | Prisma.VacancyApplicationWhereInput[]
  id?: Prisma.UuidFilter<"VacancyApplication"> | string
  vacancyId?: Prisma.UuidFilter<"VacancyApplication"> | string
  userId?: Prisma.UuidFilter<"VacancyApplication"> | string
  statusId?: Prisma.UuidFilter<"VacancyApplication"> | string
  appliedAt?: Prisma.DateTimeFilter<"VacancyApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VacancyApplication"> | Date | string
  vacancy?: Prisma.XOR<Prisma.VacancyScalarRelationFilter, Prisma.VacancyWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  status?: Prisma.XOR<Prisma.ApplicationStatusScalarRelationFilter, Prisma.ApplicationStatusWhereInput>
  history?: Prisma.ApplicationHistoryListRelationFilter
}

export type VacancyApplicationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  appliedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  vacancy?: Prisma.VacancyOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  status?: Prisma.ApplicationStatusOrderByWithRelationInput
  history?: Prisma.ApplicationHistoryOrderByRelationAggregateInput
}

export type VacancyApplicationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_vacancyId?: Prisma.VacancyApplicationUserIdVacancyIdCompoundUniqueInput
  AND?: Prisma.VacancyApplicationWhereInput | Prisma.VacancyApplicationWhereInput[]
  OR?: Prisma.VacancyApplicationWhereInput[]
  NOT?: Prisma.VacancyApplicationWhereInput | Prisma.VacancyApplicationWhereInput[]
  vacancyId?: Prisma.UuidFilter<"VacancyApplication"> | string
  userId?: Prisma.UuidFilter<"VacancyApplication"> | string
  statusId?: Prisma.UuidFilter<"VacancyApplication"> | string
  appliedAt?: Prisma.DateTimeFilter<"VacancyApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VacancyApplication"> | Date | string
  vacancy?: Prisma.XOR<Prisma.VacancyScalarRelationFilter, Prisma.VacancyWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  status?: Prisma.XOR<Prisma.ApplicationStatusScalarRelationFilter, Prisma.ApplicationStatusWhereInput>
  history?: Prisma.ApplicationHistoryListRelationFilter
}, "id" | "userId_vacancyId">

export type VacancyApplicationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  appliedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.VacancyApplicationCountOrderByAggregateInput
  _max?: Prisma.VacancyApplicationMaxOrderByAggregateInput
  _min?: Prisma.VacancyApplicationMinOrderByAggregateInput
}

export type VacancyApplicationScalarWhereWithAggregatesInput = {
  AND?: Prisma.VacancyApplicationScalarWhereWithAggregatesInput | Prisma.VacancyApplicationScalarWhereWithAggregatesInput[]
  OR?: Prisma.VacancyApplicationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.VacancyApplicationScalarWhereWithAggregatesInput | Prisma.VacancyApplicationScalarWhereWithAggregatesInput[]
  id?: Prisma.UuidWithAggregatesFilter<"VacancyApplication"> | string
  vacancyId?: Prisma.UuidWithAggregatesFilter<"VacancyApplication"> | string
  userId?: Prisma.UuidWithAggregatesFilter<"VacancyApplication"> | string
  statusId?: Prisma.UuidWithAggregatesFilter<"VacancyApplication"> | string
  appliedAt?: Prisma.DateTimeWithAggregatesFilter<"VacancyApplication"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"VacancyApplication"> | Date | string
}

export type VacancyApplicationCreateInput = {
  id?: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  vacancy: Prisma.VacancyCreateNestedOneWithoutApplicationsInput
  user: Prisma.UserCreateNestedOneWithoutVacancyApplicationsInput
  status: Prisma.ApplicationStatusCreateNestedOneWithoutApplicationsInput
  history?: Prisma.ApplicationHistoryCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationUncheckedCreateInput = {
  id?: string
  vacancyId: string
  userId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  history?: Prisma.ApplicationHistoryUncheckedCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vacancy?: Prisma.VacancyUpdateOneRequiredWithoutApplicationsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVacancyApplicationsNestedInput
  status?: Prisma.ApplicationStatusUpdateOneRequiredWithoutApplicationsNestedInput
  history?: Prisma.ApplicationHistoryUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  history?: Prisma.ApplicationHistoryUncheckedUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationCreateManyInput = {
  id?: string
  vacancyId: string
  userId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
}

export type VacancyApplicationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VacancyApplicationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VacancyApplicationListRelationFilter = {
  every?: Prisma.VacancyApplicationWhereInput
  some?: Prisma.VacancyApplicationWhereInput
  none?: Prisma.VacancyApplicationWhereInput
}

export type VacancyApplicationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type VacancyApplicationUserIdVacancyIdCompoundUniqueInput = {
  userId: string
  vacancyId: string
}

export type VacancyApplicationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  appliedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VacancyApplicationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  appliedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VacancyApplicationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  vacancyId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  statusId?: Prisma.SortOrder
  appliedAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type VacancyApplicationScalarRelationFilter = {
  is?: Prisma.VacancyApplicationWhereInput
  isNot?: Prisma.VacancyApplicationWhereInput
}

export type VacancyApplicationCreateNestedManyWithoutVacancyInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput> | Prisma.VacancyApplicationCreateWithoutVacancyInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput | Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput[]
  createMany?: Prisma.VacancyApplicationCreateManyVacancyInputEnvelope
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
}

export type VacancyApplicationUncheckedCreateNestedManyWithoutVacancyInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput> | Prisma.VacancyApplicationCreateWithoutVacancyInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput | Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput[]
  createMany?: Prisma.VacancyApplicationCreateManyVacancyInputEnvelope
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
}

export type VacancyApplicationUpdateManyWithoutVacancyNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput> | Prisma.VacancyApplicationCreateWithoutVacancyInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput | Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput[]
  upsert?: Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutVacancyInput | Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutVacancyInput[]
  createMany?: Prisma.VacancyApplicationCreateManyVacancyInputEnvelope
  set?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  disconnect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  delete?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  update?: Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutVacancyInput | Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutVacancyInput[]
  updateMany?: Prisma.VacancyApplicationUpdateManyWithWhereWithoutVacancyInput | Prisma.VacancyApplicationUpdateManyWithWhereWithoutVacancyInput[]
  deleteMany?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
}

export type VacancyApplicationUncheckedUpdateManyWithoutVacancyNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput> | Prisma.VacancyApplicationCreateWithoutVacancyInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput | Prisma.VacancyApplicationCreateOrConnectWithoutVacancyInput[]
  upsert?: Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutVacancyInput | Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutVacancyInput[]
  createMany?: Prisma.VacancyApplicationCreateManyVacancyInputEnvelope
  set?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  disconnect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  delete?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  update?: Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutVacancyInput | Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutVacancyInput[]
  updateMany?: Prisma.VacancyApplicationUpdateManyWithWhereWithoutVacancyInput | Prisma.VacancyApplicationUpdateManyWithWhereWithoutVacancyInput[]
  deleteMany?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
}

export type VacancyApplicationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutUserInput, Prisma.VacancyApplicationUncheckedCreateWithoutUserInput> | Prisma.VacancyApplicationCreateWithoutUserInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutUserInput | Prisma.VacancyApplicationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.VacancyApplicationCreateManyUserInputEnvelope
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
}

export type VacancyApplicationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutUserInput, Prisma.VacancyApplicationUncheckedCreateWithoutUserInput> | Prisma.VacancyApplicationCreateWithoutUserInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutUserInput | Prisma.VacancyApplicationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.VacancyApplicationCreateManyUserInputEnvelope
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
}

export type VacancyApplicationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutUserInput, Prisma.VacancyApplicationUncheckedCreateWithoutUserInput> | Prisma.VacancyApplicationCreateWithoutUserInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutUserInput | Prisma.VacancyApplicationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutUserInput | Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.VacancyApplicationCreateManyUserInputEnvelope
  set?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  disconnect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  delete?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  update?: Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutUserInput | Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.VacancyApplicationUpdateManyWithWhereWithoutUserInput | Prisma.VacancyApplicationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
}

export type VacancyApplicationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutUserInput, Prisma.VacancyApplicationUncheckedCreateWithoutUserInput> | Prisma.VacancyApplicationCreateWithoutUserInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutUserInput | Prisma.VacancyApplicationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutUserInput | Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.VacancyApplicationCreateManyUserInputEnvelope
  set?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  disconnect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  delete?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  update?: Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutUserInput | Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.VacancyApplicationUpdateManyWithWhereWithoutUserInput | Prisma.VacancyApplicationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
}

export type VacancyApplicationCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutStatusInput, Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput> | Prisma.VacancyApplicationCreateWithoutStatusInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput | Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.VacancyApplicationCreateManyStatusInputEnvelope
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
}

export type VacancyApplicationUncheckedCreateNestedManyWithoutStatusInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutStatusInput, Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput> | Prisma.VacancyApplicationCreateWithoutStatusInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput | Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput[]
  createMany?: Prisma.VacancyApplicationCreateManyStatusInputEnvelope
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
}

export type VacancyApplicationUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutStatusInput, Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput> | Prisma.VacancyApplicationCreateWithoutStatusInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput | Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutStatusInput | Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.VacancyApplicationCreateManyStatusInputEnvelope
  set?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  disconnect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  delete?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  update?: Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutStatusInput | Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.VacancyApplicationUpdateManyWithWhereWithoutStatusInput | Prisma.VacancyApplicationUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
}

export type VacancyApplicationUncheckedUpdateManyWithoutStatusNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutStatusInput, Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput> | Prisma.VacancyApplicationCreateWithoutStatusInput[] | Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput[]
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput | Prisma.VacancyApplicationCreateOrConnectWithoutStatusInput[]
  upsert?: Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutStatusInput | Prisma.VacancyApplicationUpsertWithWhereUniqueWithoutStatusInput[]
  createMany?: Prisma.VacancyApplicationCreateManyStatusInputEnvelope
  set?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  disconnect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  delete?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  connect?: Prisma.VacancyApplicationWhereUniqueInput | Prisma.VacancyApplicationWhereUniqueInput[]
  update?: Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutStatusInput | Prisma.VacancyApplicationUpdateWithWhereUniqueWithoutStatusInput[]
  updateMany?: Prisma.VacancyApplicationUpdateManyWithWhereWithoutStatusInput | Prisma.VacancyApplicationUpdateManyWithWhereWithoutStatusInput[]
  deleteMany?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
}

export type VacancyApplicationCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutHistoryInput, Prisma.VacancyApplicationUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutHistoryInput
  connect?: Prisma.VacancyApplicationWhereUniqueInput
}

export type VacancyApplicationUpdateOneRequiredWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutHistoryInput, Prisma.VacancyApplicationUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.VacancyApplicationCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.VacancyApplicationUpsertWithoutHistoryInput
  connect?: Prisma.VacancyApplicationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.VacancyApplicationUpdateToOneWithWhereWithoutHistoryInput, Prisma.VacancyApplicationUpdateWithoutHistoryInput>, Prisma.VacancyApplicationUncheckedUpdateWithoutHistoryInput>
}

export type VacancyApplicationCreateWithoutVacancyInput = {
  id?: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutVacancyApplicationsInput
  status: Prisma.ApplicationStatusCreateNestedOneWithoutApplicationsInput
  history?: Prisma.ApplicationHistoryCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationUncheckedCreateWithoutVacancyInput = {
  id?: string
  userId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  history?: Prisma.ApplicationHistoryUncheckedCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationCreateOrConnectWithoutVacancyInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput>
}

export type VacancyApplicationCreateManyVacancyInputEnvelope = {
  data: Prisma.VacancyApplicationCreateManyVacancyInput | Prisma.VacancyApplicationCreateManyVacancyInput[]
  skipDuplicates?: boolean
}

export type VacancyApplicationUpsertWithWhereUniqueWithoutVacancyInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  update: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedUpdateWithoutVacancyInput>
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedCreateWithoutVacancyInput>
}

export type VacancyApplicationUpdateWithWhereUniqueWithoutVacancyInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutVacancyInput, Prisma.VacancyApplicationUncheckedUpdateWithoutVacancyInput>
}

export type VacancyApplicationUpdateManyWithWhereWithoutVacancyInput = {
  where: Prisma.VacancyApplicationScalarWhereInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateManyMutationInput, Prisma.VacancyApplicationUncheckedUpdateManyWithoutVacancyInput>
}

export type VacancyApplicationScalarWhereInput = {
  AND?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
  OR?: Prisma.VacancyApplicationScalarWhereInput[]
  NOT?: Prisma.VacancyApplicationScalarWhereInput | Prisma.VacancyApplicationScalarWhereInput[]
  id?: Prisma.UuidFilter<"VacancyApplication"> | string
  vacancyId?: Prisma.UuidFilter<"VacancyApplication"> | string
  userId?: Prisma.UuidFilter<"VacancyApplication"> | string
  statusId?: Prisma.UuidFilter<"VacancyApplication"> | string
  appliedAt?: Prisma.DateTimeFilter<"VacancyApplication"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"VacancyApplication"> | Date | string
}

export type VacancyApplicationCreateWithoutUserInput = {
  id?: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  vacancy: Prisma.VacancyCreateNestedOneWithoutApplicationsInput
  status: Prisma.ApplicationStatusCreateNestedOneWithoutApplicationsInput
  history?: Prisma.ApplicationHistoryCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationUncheckedCreateWithoutUserInput = {
  id?: string
  vacancyId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  history?: Prisma.ApplicationHistoryUncheckedCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationCreateOrConnectWithoutUserInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutUserInput, Prisma.VacancyApplicationUncheckedCreateWithoutUserInput>
}

export type VacancyApplicationCreateManyUserInputEnvelope = {
  data: Prisma.VacancyApplicationCreateManyUserInput | Prisma.VacancyApplicationCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type VacancyApplicationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  update: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutUserInput, Prisma.VacancyApplicationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutUserInput, Prisma.VacancyApplicationUncheckedCreateWithoutUserInput>
}

export type VacancyApplicationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutUserInput, Prisma.VacancyApplicationUncheckedUpdateWithoutUserInput>
}

export type VacancyApplicationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.VacancyApplicationScalarWhereInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateManyMutationInput, Prisma.VacancyApplicationUncheckedUpdateManyWithoutUserInput>
}

export type VacancyApplicationCreateWithoutStatusInput = {
  id?: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  vacancy: Prisma.VacancyCreateNestedOneWithoutApplicationsInput
  user: Prisma.UserCreateNestedOneWithoutVacancyApplicationsInput
  history?: Prisma.ApplicationHistoryCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationUncheckedCreateWithoutStatusInput = {
  id?: string
  vacancyId: string
  userId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  history?: Prisma.ApplicationHistoryUncheckedCreateNestedManyWithoutApplicationInput
}

export type VacancyApplicationCreateOrConnectWithoutStatusInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutStatusInput, Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput>
}

export type VacancyApplicationCreateManyStatusInputEnvelope = {
  data: Prisma.VacancyApplicationCreateManyStatusInput | Prisma.VacancyApplicationCreateManyStatusInput[]
  skipDuplicates?: boolean
}

export type VacancyApplicationUpsertWithWhereUniqueWithoutStatusInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  update: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutStatusInput, Prisma.VacancyApplicationUncheckedUpdateWithoutStatusInput>
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutStatusInput, Prisma.VacancyApplicationUncheckedCreateWithoutStatusInput>
}

export type VacancyApplicationUpdateWithWhereUniqueWithoutStatusInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutStatusInput, Prisma.VacancyApplicationUncheckedUpdateWithoutStatusInput>
}

export type VacancyApplicationUpdateManyWithWhereWithoutStatusInput = {
  where: Prisma.VacancyApplicationScalarWhereInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateManyMutationInput, Prisma.VacancyApplicationUncheckedUpdateManyWithoutStatusInput>
}

export type VacancyApplicationCreateWithoutHistoryInput = {
  id?: string
  appliedAt?: Date | string
  updatedAt?: Date | string
  vacancy: Prisma.VacancyCreateNestedOneWithoutApplicationsInput
  user: Prisma.UserCreateNestedOneWithoutVacancyApplicationsInput
  status: Prisma.ApplicationStatusCreateNestedOneWithoutApplicationsInput
}

export type VacancyApplicationUncheckedCreateWithoutHistoryInput = {
  id?: string
  vacancyId: string
  userId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
}

export type VacancyApplicationCreateOrConnectWithoutHistoryInput = {
  where: Prisma.VacancyApplicationWhereUniqueInput
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutHistoryInput, Prisma.VacancyApplicationUncheckedCreateWithoutHistoryInput>
}

export type VacancyApplicationUpsertWithoutHistoryInput = {
  update: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutHistoryInput, Prisma.VacancyApplicationUncheckedUpdateWithoutHistoryInput>
  create: Prisma.XOR<Prisma.VacancyApplicationCreateWithoutHistoryInput, Prisma.VacancyApplicationUncheckedCreateWithoutHistoryInput>
  where?: Prisma.VacancyApplicationWhereInput
}

export type VacancyApplicationUpdateToOneWithWhereWithoutHistoryInput = {
  where?: Prisma.VacancyApplicationWhereInput
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateWithoutHistoryInput, Prisma.VacancyApplicationUncheckedUpdateWithoutHistoryInput>
}

export type VacancyApplicationUpdateWithoutHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vacancy?: Prisma.VacancyUpdateOneRequiredWithoutApplicationsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVacancyApplicationsNestedInput
  status?: Prisma.ApplicationStatusUpdateOneRequiredWithoutApplicationsNestedInput
}

export type VacancyApplicationUncheckedUpdateWithoutHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VacancyApplicationCreateManyVacancyInput = {
  id?: string
  userId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
}

export type VacancyApplicationUpdateWithoutVacancyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutVacancyApplicationsNestedInput
  status?: Prisma.ApplicationStatusUpdateOneRequiredWithoutApplicationsNestedInput
  history?: Prisma.ApplicationHistoryUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateWithoutVacancyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  history?: Prisma.ApplicationHistoryUncheckedUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateManyWithoutVacancyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VacancyApplicationCreateManyUserInput = {
  id?: string
  vacancyId: string
  statusId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
}

export type VacancyApplicationUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vacancy?: Prisma.VacancyUpdateOneRequiredWithoutApplicationsNestedInput
  status?: Prisma.ApplicationStatusUpdateOneRequiredWithoutApplicationsNestedInput
  history?: Prisma.ApplicationHistoryUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  history?: Prisma.ApplicationHistoryUncheckedUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  statusId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type VacancyApplicationCreateManyStatusInput = {
  id?: string
  vacancyId: string
  userId: string
  appliedAt?: Date | string
  updatedAt?: Date | string
}

export type VacancyApplicationUpdateWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  vacancy?: Prisma.VacancyUpdateOneRequiredWithoutApplicationsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutVacancyApplicationsNestedInput
  history?: Prisma.ApplicationHistoryUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  history?: Prisma.ApplicationHistoryUncheckedUpdateManyWithoutApplicationNestedInput
}

export type VacancyApplicationUncheckedUpdateManyWithoutStatusInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  vacancyId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type VacancyApplicationCountOutputType
 */

export type VacancyApplicationCountOutputType = {
  history: number
}

export type VacancyApplicationCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  history?: boolean | VacancyApplicationCountOutputTypeCountHistoryArgs
}

/**
 * VacancyApplicationCountOutputType without action
 */
export type VacancyApplicationCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplicationCountOutputType
   */
  select?: Prisma.VacancyApplicationCountOutputTypeSelect<ExtArgs> | null
}

/**
 * VacancyApplicationCountOutputType without action
 */
export type VacancyApplicationCountOutputTypeCountHistoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ApplicationHistoryWhereInput
}


export type VacancyApplicationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vacancyId?: boolean
  userId?: boolean
  statusId?: boolean
  appliedAt?: boolean
  updatedAt?: boolean
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  history?: boolean | Prisma.VacancyApplication$historyArgs<ExtArgs>
  _count?: boolean | Prisma.VacancyApplicationCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vacancyApplication"]>

export type VacancyApplicationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vacancyId?: boolean
  userId?: boolean
  statusId?: boolean
  appliedAt?: boolean
  updatedAt?: boolean
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vacancyApplication"]>

export type VacancyApplicationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  vacancyId?: boolean
  userId?: boolean
  statusId?: boolean
  appliedAt?: boolean
  updatedAt?: boolean
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
}, ExtArgs["result"]["vacancyApplication"]>

export type VacancyApplicationSelectScalar = {
  id?: boolean
  vacancyId?: boolean
  userId?: boolean
  statusId?: boolean
  appliedAt?: boolean
  updatedAt?: boolean
}

export type VacancyApplicationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "vacancyId" | "userId" | "statusId" | "appliedAt" | "updatedAt", ExtArgs["result"]["vacancyApplication"]>
export type VacancyApplicationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
  history?: boolean | Prisma.VacancyApplication$historyArgs<ExtArgs>
  _count?: boolean | Prisma.VacancyApplicationCountOutputTypeDefaultArgs<ExtArgs>
}
export type VacancyApplicationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
}
export type VacancyApplicationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  vacancy?: boolean | Prisma.VacancyDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  status?: boolean | Prisma.ApplicationStatusDefaultArgs<ExtArgs>
}

export type $VacancyApplicationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "VacancyApplication"
  objects: {
    vacancy: Prisma.$VacancyPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    status: Prisma.$ApplicationStatusPayload<ExtArgs>
    history: Prisma.$ApplicationHistoryPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    vacancyId: string
    userId: string
    statusId: string
    appliedAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["vacancyApplication"]>
  composites: {}
}

export type VacancyApplicationGetPayload<S extends boolean | null | undefined | VacancyApplicationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload, S>

export type VacancyApplicationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<VacancyApplicationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: VacancyApplicationCountAggregateInputType | true
  }

export interface VacancyApplicationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['VacancyApplication'], meta: { name: 'VacancyApplication' } }
  /**
   * Find zero or one VacancyApplication that matches the filter.
   * @param {VacancyApplicationFindUniqueArgs} args - Arguments to find a VacancyApplication
   * @example
   * // Get one VacancyApplication
   * const vacancyApplication = await prisma.vacancyApplication.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends VacancyApplicationFindUniqueArgs>(args: Prisma.SelectSubset<T, VacancyApplicationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one VacancyApplication that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {VacancyApplicationFindUniqueOrThrowArgs} args - Arguments to find a VacancyApplication
   * @example
   * // Get one VacancyApplication
   * const vacancyApplication = await prisma.vacancyApplication.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends VacancyApplicationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, VacancyApplicationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VacancyApplication that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationFindFirstArgs} args - Arguments to find a VacancyApplication
   * @example
   * // Get one VacancyApplication
   * const vacancyApplication = await prisma.vacancyApplication.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends VacancyApplicationFindFirstArgs>(args?: Prisma.SelectSubset<T, VacancyApplicationFindFirstArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first VacancyApplication that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationFindFirstOrThrowArgs} args - Arguments to find a VacancyApplication
   * @example
   * // Get one VacancyApplication
   * const vacancyApplication = await prisma.vacancyApplication.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends VacancyApplicationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, VacancyApplicationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more VacancyApplications that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all VacancyApplications
   * const vacancyApplications = await prisma.vacancyApplication.findMany()
   * 
   * // Get first 10 VacancyApplications
   * const vacancyApplications = await prisma.vacancyApplication.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const vacancyApplicationWithIdOnly = await prisma.vacancyApplication.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends VacancyApplicationFindManyArgs>(args?: Prisma.SelectSubset<T, VacancyApplicationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a VacancyApplication.
   * @param {VacancyApplicationCreateArgs} args - Arguments to create a VacancyApplication.
   * @example
   * // Create one VacancyApplication
   * const VacancyApplication = await prisma.vacancyApplication.create({
   *   data: {
   *     // ... data to create a VacancyApplication
   *   }
   * })
   * 
   */
  create<T extends VacancyApplicationCreateArgs>(args: Prisma.SelectSubset<T, VacancyApplicationCreateArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many VacancyApplications.
   * @param {VacancyApplicationCreateManyArgs} args - Arguments to create many VacancyApplications.
   * @example
   * // Create many VacancyApplications
   * const vacancyApplication = await prisma.vacancyApplication.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends VacancyApplicationCreateManyArgs>(args?: Prisma.SelectSubset<T, VacancyApplicationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many VacancyApplications and returns the data saved in the database.
   * @param {VacancyApplicationCreateManyAndReturnArgs} args - Arguments to create many VacancyApplications.
   * @example
   * // Create many VacancyApplications
   * const vacancyApplication = await prisma.vacancyApplication.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many VacancyApplications and only return the `id`
   * const vacancyApplicationWithIdOnly = await prisma.vacancyApplication.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends VacancyApplicationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, VacancyApplicationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a VacancyApplication.
   * @param {VacancyApplicationDeleteArgs} args - Arguments to delete one VacancyApplication.
   * @example
   * // Delete one VacancyApplication
   * const VacancyApplication = await prisma.vacancyApplication.delete({
   *   where: {
   *     // ... filter to delete one VacancyApplication
   *   }
   * })
   * 
   */
  delete<T extends VacancyApplicationDeleteArgs>(args: Prisma.SelectSubset<T, VacancyApplicationDeleteArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one VacancyApplication.
   * @param {VacancyApplicationUpdateArgs} args - Arguments to update one VacancyApplication.
   * @example
   * // Update one VacancyApplication
   * const vacancyApplication = await prisma.vacancyApplication.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends VacancyApplicationUpdateArgs>(args: Prisma.SelectSubset<T, VacancyApplicationUpdateArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more VacancyApplications.
   * @param {VacancyApplicationDeleteManyArgs} args - Arguments to filter VacancyApplications to delete.
   * @example
   * // Delete a few VacancyApplications
   * const { count } = await prisma.vacancyApplication.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends VacancyApplicationDeleteManyArgs>(args?: Prisma.SelectSubset<T, VacancyApplicationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VacancyApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many VacancyApplications
   * const vacancyApplication = await prisma.vacancyApplication.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends VacancyApplicationUpdateManyArgs>(args: Prisma.SelectSubset<T, VacancyApplicationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more VacancyApplications and returns the data updated in the database.
   * @param {VacancyApplicationUpdateManyAndReturnArgs} args - Arguments to update many VacancyApplications.
   * @example
   * // Update many VacancyApplications
   * const vacancyApplication = await prisma.vacancyApplication.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more VacancyApplications and only return the `id`
   * const vacancyApplicationWithIdOnly = await prisma.vacancyApplication.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends VacancyApplicationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, VacancyApplicationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one VacancyApplication.
   * @param {VacancyApplicationUpsertArgs} args - Arguments to update or create a VacancyApplication.
   * @example
   * // Update or create a VacancyApplication
   * const vacancyApplication = await prisma.vacancyApplication.upsert({
   *   create: {
   *     // ... data to create a VacancyApplication
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the VacancyApplication we want to update
   *   }
   * })
   */
  upsert<T extends VacancyApplicationUpsertArgs>(args: Prisma.SelectSubset<T, VacancyApplicationUpsertArgs<ExtArgs>>): Prisma.Prisma__VacancyApplicationClient<runtime.Types.Result.GetResult<Prisma.$VacancyApplicationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of VacancyApplications.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationCountArgs} args - Arguments to filter VacancyApplications to count.
   * @example
   * // Count the number of VacancyApplications
   * const count = await prisma.vacancyApplication.count({
   *   where: {
   *     // ... the filter for the VacancyApplications we want to count
   *   }
   * })
  **/
  count<T extends VacancyApplicationCountArgs>(
    args?: Prisma.Subset<T, VacancyApplicationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], VacancyApplicationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a VacancyApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends VacancyApplicationAggregateArgs>(args: Prisma.Subset<T, VacancyApplicationAggregateArgs>): Prisma.PrismaPromise<GetVacancyApplicationAggregateType<T>>

  /**
   * Group by VacancyApplication.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {VacancyApplicationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends VacancyApplicationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: VacancyApplicationGroupByArgs['orderBy'] }
      : { orderBy?: VacancyApplicationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, VacancyApplicationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVacancyApplicationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the VacancyApplication model
 */
readonly fields: VacancyApplicationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for VacancyApplication.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__VacancyApplicationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  vacancy<T extends Prisma.VacancyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VacancyDefaultArgs<ExtArgs>>): Prisma.Prisma__VacancyClient<runtime.Types.Result.GetResult<Prisma.$VacancyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  status<T extends Prisma.ApplicationStatusDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ApplicationStatusDefaultArgs<ExtArgs>>): Prisma.Prisma__ApplicationStatusClient<runtime.Types.Result.GetResult<Prisma.$ApplicationStatusPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  history<T extends Prisma.VacancyApplication$historyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.VacancyApplication$historyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ApplicationHistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the VacancyApplication model
 */
export interface VacancyApplicationFieldRefs {
  readonly id: Prisma.FieldRef<"VacancyApplication", 'String'>
  readonly vacancyId: Prisma.FieldRef<"VacancyApplication", 'String'>
  readonly userId: Prisma.FieldRef<"VacancyApplication", 'String'>
  readonly statusId: Prisma.FieldRef<"VacancyApplication", 'String'>
  readonly appliedAt: Prisma.FieldRef<"VacancyApplication", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"VacancyApplication", 'DateTime'>
}
    

// Custom InputTypes
/**
 * VacancyApplication findUnique
 */
export type VacancyApplicationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * Filter, which VacancyApplication to fetch.
   */
  where: Prisma.VacancyApplicationWhereUniqueInput
}

/**
 * VacancyApplication findUniqueOrThrow
 */
export type VacancyApplicationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * Filter, which VacancyApplication to fetch.
   */
  where: Prisma.VacancyApplicationWhereUniqueInput
}

/**
 * VacancyApplication findFirst
 */
export type VacancyApplicationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * Filter, which VacancyApplication to fetch.
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VacancyApplications to fetch.
   */
  orderBy?: Prisma.VacancyApplicationOrderByWithRelationInput | Prisma.VacancyApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VacancyApplications.
   */
  cursor?: Prisma.VacancyApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VacancyApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VacancyApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VacancyApplications.
   */
  distinct?: Prisma.VacancyApplicationScalarFieldEnum | Prisma.VacancyApplicationScalarFieldEnum[]
}

/**
 * VacancyApplication findFirstOrThrow
 */
export type VacancyApplicationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * Filter, which VacancyApplication to fetch.
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VacancyApplications to fetch.
   */
  orderBy?: Prisma.VacancyApplicationOrderByWithRelationInput | Prisma.VacancyApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for VacancyApplications.
   */
  cursor?: Prisma.VacancyApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VacancyApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VacancyApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VacancyApplications.
   */
  distinct?: Prisma.VacancyApplicationScalarFieldEnum | Prisma.VacancyApplicationScalarFieldEnum[]
}

/**
 * VacancyApplication findMany
 */
export type VacancyApplicationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * Filter, which VacancyApplications to fetch.
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of VacancyApplications to fetch.
   */
  orderBy?: Prisma.VacancyApplicationOrderByWithRelationInput | Prisma.VacancyApplicationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing VacancyApplications.
   */
  cursor?: Prisma.VacancyApplicationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` VacancyApplications from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` VacancyApplications.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of VacancyApplications.
   */
  distinct?: Prisma.VacancyApplicationScalarFieldEnum | Prisma.VacancyApplicationScalarFieldEnum[]
}

/**
 * VacancyApplication create
 */
export type VacancyApplicationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * The data needed to create a VacancyApplication.
   */
  data: Prisma.XOR<Prisma.VacancyApplicationCreateInput, Prisma.VacancyApplicationUncheckedCreateInput>
}

/**
 * VacancyApplication createMany
 */
export type VacancyApplicationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many VacancyApplications.
   */
  data: Prisma.VacancyApplicationCreateManyInput | Prisma.VacancyApplicationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * VacancyApplication createManyAndReturn
 */
export type VacancyApplicationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * The data used to create many VacancyApplications.
   */
  data: Prisma.VacancyApplicationCreateManyInput | Prisma.VacancyApplicationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * VacancyApplication update
 */
export type VacancyApplicationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * The data needed to update a VacancyApplication.
   */
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateInput, Prisma.VacancyApplicationUncheckedUpdateInput>
  /**
   * Choose, which VacancyApplication to update.
   */
  where: Prisma.VacancyApplicationWhereUniqueInput
}

/**
 * VacancyApplication updateMany
 */
export type VacancyApplicationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update VacancyApplications.
   */
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateManyMutationInput, Prisma.VacancyApplicationUncheckedUpdateManyInput>
  /**
   * Filter which VacancyApplications to update
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * Limit how many VacancyApplications to update.
   */
  limit?: number
}

/**
 * VacancyApplication updateManyAndReturn
 */
export type VacancyApplicationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * The data used to update VacancyApplications.
   */
  data: Prisma.XOR<Prisma.VacancyApplicationUpdateManyMutationInput, Prisma.VacancyApplicationUncheckedUpdateManyInput>
  /**
   * Filter which VacancyApplications to update
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * Limit how many VacancyApplications to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * VacancyApplication upsert
 */
export type VacancyApplicationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * The filter to search for the VacancyApplication to update in case it exists.
   */
  where: Prisma.VacancyApplicationWhereUniqueInput
  /**
   * In case the VacancyApplication found by the `where` argument doesn't exist, create a new VacancyApplication with this data.
   */
  create: Prisma.XOR<Prisma.VacancyApplicationCreateInput, Prisma.VacancyApplicationUncheckedCreateInput>
  /**
   * In case the VacancyApplication was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.VacancyApplicationUpdateInput, Prisma.VacancyApplicationUncheckedUpdateInput>
}

/**
 * VacancyApplication delete
 */
export type VacancyApplicationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
  /**
   * Filter which VacancyApplication to delete.
   */
  where: Prisma.VacancyApplicationWhereUniqueInput
}

/**
 * VacancyApplication deleteMany
 */
export type VacancyApplicationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which VacancyApplications to delete
   */
  where?: Prisma.VacancyApplicationWhereInput
  /**
   * Limit how many VacancyApplications to delete.
   */
  limit?: number
}

/**
 * VacancyApplication.history
 */
export type VacancyApplication$historyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ApplicationHistory
   */
  select?: Prisma.ApplicationHistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the ApplicationHistory
   */
  omit?: Prisma.ApplicationHistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ApplicationHistoryInclude<ExtArgs> | null
  where?: Prisma.ApplicationHistoryWhereInput
  orderBy?: Prisma.ApplicationHistoryOrderByWithRelationInput | Prisma.ApplicationHistoryOrderByWithRelationInput[]
  cursor?: Prisma.ApplicationHistoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ApplicationHistoryScalarFieldEnum | Prisma.ApplicationHistoryScalarFieldEnum[]
}

/**
 * VacancyApplication without action
 */
export type VacancyApplicationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the VacancyApplication
   */
  select?: Prisma.VacancyApplicationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the VacancyApplication
   */
  omit?: Prisma.VacancyApplicationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.VacancyApplicationInclude<ExtArgs> | null
}
