import { ACCESS_REQUEST_STATUS } from '../types/access-request.enum.js';

export const ACTIVE_STATUSES: string[] = [
  ACCESS_REQUEST_STATUS.PENDING,
  ACCESS_REQUEST_STATUS.IN_REVIEW,
  ACCESS_REQUEST_STATUS.APPROVED,
];

export const LISTED_STATUSES: string[] = [
  ACCESS_REQUEST_STATUS.PENDING,
  ACCESS_REQUEST_STATUS.IN_REVIEW,
  ACCESS_REQUEST_STATUS.APPROVED,
  ACCESS_REQUEST_STATUS.REJECTED,
];
