import { ACCESS_REQUEST_STATUS } from '../types/access-request.enum.js';

export const LIST_STATUSES = [
  ACCESS_REQUEST_STATUS.PENDING,
  ACCESS_REQUEST_STATUS.IN_REVIEW,
  ACCESS_REQUEST_STATUS.APPROVED,
  ACCESS_REQUEST_STATUS.REJECTED,
] as const;

export const DEFAULT_PAGE_SIZE = 10;

export const MAX_PAGE_SIZE = 50;
